#!/usr/bin/env python3
"""
Write each week page's "what this unit assumes" block from the
readiness data, so the two never drift apart.

    python3 tools/build-unit-prereqs.py            # every week page
    python3 tools/build-unit-prereqs.py week-01.html

WHY THIS IS GENERATED AND NOT TYPED
-----------------------------------
before-you-start.html is course wide on purpose: 27 concepts across
chemistry, anatomy and math, taken once before the term. That is the
right shape for a front door and the wrong shape for a Monday. A
student opening unit 1 does not need to be told the nephron is coming;
they need the two anatomy concepts unit 1 actually uses.

Each concept in readiness-check.js carries a units array. This reads
it and writes the matching block into the page between two markers. Fix
a concept's units once, rerun, and all fifteen pages are correct. Typing
the block by hand means fifteen chances to get it wrong and no way to
notice when one is.

The block is written as plain static HTML rather than rendered at run
time. Week pages have no data dependency today, the reading mode and
the print stylesheet both work on real markup, and a generated block
that is in the file can be read in a diff.
"""
import json, os, re, subprocess, sys

START = '<!-- UNIT-PREREQS:START  generated by tools/build-unit-prereqs.py, do not edit by hand -->'
END   = '<!-- UNIT-PREREQS:END -->'

# Week to unit. Matches BIO005_MODULES: 1 to 3, 4 to 6, 7 to 9, 10 to 12, 13 to 15.
def unit_of(week):
    return 1 if week <= 3 else 2 if week <= 6 else 3 if week <= 9 else 4 if week <= 12 else 5

UNIT_NAME = {
    1: 'Unit 1',
    2: 'Unit 2',
    3: 'Unit 3',
    4: 'Unit 4',
    5: 'Unit 5',
}

BOX = [('chemistry', 'Chemistry', 'chem'),
       ('anatomy',   'Anatomy',   'anat'),
       ('math',      'Math',      'math')]


def load_readiness(root):
    """Read the data through node, so this file never re-parses JS by hand."""
    js = ('global.window={};require(%s);'
          'process.stdout.write(JSON.stringify(global.window.BIO005_READINESS));'
          % json.dumps(os.path.join(root, 'readiness-check.js')))
    out = subprocess.run(['node', '-e', js], capture_output=True, text=True)
    if out.returncode:
        print(out.stderr.strip())
        return None
    return json.loads(out.stdout)


def esc(t):
    return (t.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;'))


def block(data, unit):
    rows = []
    total = 0
    grand = sum(len(data[k]['concepts']) for k, _, _ in BOX)
    for key, label, anchor in BOX:
        cs = [c for c in data[key]['concepts'] if unit in c.get('units', [])]
        if not cs:
            continue
        total += len(cs)
        names = ' '.join('<a href="unit-%02d.html#%s" target="_top">%s</a>'
                         % (unit, anchor, esc(c['name'])) for c in cs)
        rows.append('          <div class="up-row">\n'
                    '            <p class="up-k">%s</p>\n'
                    '            <p class="up-v">%s</p>\n'
                    '          </div>' % (esc(label), names))

    return (START + '\n'
            '      <div class="unitprereq">\n'
            '        <p class="up-l">What %s assumes you already have</p>\n'
            '        <div class="up-grid">\n%s\n        </div>\n'
            '        <p class="up-note">Only these %d, out of the %d the whole course uses. '
            'Not the other %d, and not yet. Each one links to '
            '<a href="unit-%02d.html" target="_top">the %s page</a>, which has a short check '
            'for it and tells you what to review if you need it.</p>\n'
            '      </div>\n      ' % (UNIT_NAME[unit], '\n'.join(rows),
                                       total, grand, grand - total, unit,
                                       UNIT_NAME[unit].lower())
            + END)


CSS_MARK = '/* ---------- UNIT PREREQS ---------- */'
CSS = '''
  ''' + CSS_MARK + '''
  /* Generated block, see tools/build-unit-prereqs.py. Card, no bookend
     rule, lifts off the page like everything else. */
  .unitprereq{background:#fff;border:1px solid var(--rule);border-radius:var(--radius);
    padding:16px 20px;margin:0 0 26px;max-width:78ch;
    box-shadow:0 1px 2px rgba(8,16,31,.06), 0 8px 18px rgba(8,16,31,.09)}
  .unitprereq .up-l{font-family:var(--font-eyebrow);font-size:.66rem;font-weight:700;
    letter-spacing:.16em;text-transform:uppercase;color:var(--maroon-dark);margin:0 0 10px}
  .unitprereq .up-grid{display:grid;gap:9px}
  .unitprereq .up-row{display:grid;grid-template-columns:78px minmax(0,1fr);gap:12px;align-items:baseline}
  @media(max-width:640px){.unitprereq .up-row{grid-template-columns:1fr;gap:3px}}
  .unitprereq .up-k{font-family:var(--font-eyebrow);font-size:.68rem;font-weight:700;
    letter-spacing:.12em;text-transform:uppercase;color:var(--navy);margin:0}
  .unitprereq .up-v{margin:0;font-size:.9rem;line-height:1.5}
  .unitprereq .up-v a{display:inline-block;color:var(--navy);text-decoration:none;font-weight:500;
    border:1px solid var(--rule);border-radius:999px;padding:2px 10px;margin:0 4px 4px 0;
    transition:var(--t)}
  .unitprereq .up-v a:hover{border-color:var(--maroon-dark);background:var(--offwhite);text-decoration:none}
  .unitprereq .up-note{margin:11px 0 0;font-size:.84rem;color:var(--gray)}
  @media print{
    .unitprereq{box-shadow:none;padding:9pt 11pt;margin:0 0 12pt;break-inside:avoid}
    .unitprereq .up-v a{border:none;padding:0;margin:0 7pt 0 0;color:#414B5C}
  }
'''


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)

    data = load_readiness(root)
    if not data:
        print('Could not read readiness-check.js')
        return 1

    pages = sys.argv[1:] or sorted(
        f for f in os.listdir('.') if re.match(r'^week-\d\d\.html$', f))
    if not pages:
        print('No week pages yet. Nothing to do.')
        return 0

    for page in pages:
        m = re.match(r'^week-(\d\d)\.html$', os.path.basename(page))
        if not m:
            print('%s is not a week page, skipped' % page)
            continue
        unit = unit_of(int(m.group(1)))
        s = open(page, encoding='utf-8').read()
        new = block(data, unit)

        if START in s and END in s:
            s = re.sub(re.escape(START) + '.*?' + re.escape(END), lambda _: new, s, flags=re.S)
            how = 'refreshed'
        else:
            # First run. Goes directly after the how-to card, above the
            # first section, which is where a student looks before starting.
            am = re.search(r'\n\s*<p class="sec-eyebrow">Start here</p>', s)
            if not am:
                print('%s: no "Start here" eyebrow to anchor to, skipped' % page)
                continue
            s = s[:am.start()] + '\n    ' + new + '\n\n      <p class="sec-eyebrow">Start here</p>' + s[am.end():]
            how = 'inserted'

        if CSS_MARK not in s:
            i = s.rindex('</style>')
            s = s[:i] + CSS + '\n  ' + s[i:]

        open(page, 'w', encoding='utf-8').write(s)
        n = len(re.findall(r'class="up-v"', new))
        links = len(re.findall(r'<a href="unit-\d\d\.html#', new))
        print('%s  unit %d, %d prerequisites across %d areas, %s'
              % (page, unit, links, n, how))
    return 0


if __name__ == '__main__':
    sys.exit(main())
