"""
tools/walkthrough_notes_w04.py

The written notes that go with each Week 4 guided walkthrough. Sep 27 2026,
Scrubs: every walkthrough gets a set of real notes, not a repeat of the slides,
in bullet form, with definitions and sequences, and a printable PDF.

The content comes from the walkthroughs themselves, which were checked against
Silverthorn and the course notes when they were built. Nothing here adds a new
fact that is not already taught in the walkthrough or the Week 4 lecture notes.

Block types:  ("p", text)  ("ul", [..])  ("ol", [..])  ("defs", [(term, def)])
              ("table", [header], [[row]...])  ("h3", text)
Run: python3 tools/make_walkthrough_notes.py
"""
M = "−"

DIV = "\u00f7"
NOTES = [
 dict(slug="neurons-glia", file="biol005-w04-neurons-glia-walkthrough-notes.html",
  title="Neurons and neuroglia", walk="biol005-w04-neurons-glia-guided.html",
  comps="Week 4 competencies 7 to 11",
  sections=[
   ("The map of the nervous system", [
     ("ul", ["The central nervous system (CNS) is the brain and spinal cord. It is where information is integrated and decisions are made.",
             "The peripheral nervous system (PNS) is everything else: the nerves that carry information in and commands out.",
             "The sensory division, also called the afferent division, carries information toward the CNS from receptors in the skin, muscles, eyes, ears and internal organs. Most signals from the organs never reach awareness.",
             "The efferent division carries commands away from the CNS to effectors, which are muscles and glands."]),
     ("table", ["Efferent branch", "What it controls", "Example"],
      [["Somatic motor division", "Skeletal muscle", "Picking up a pencil on purpose; many reflexes"],
       ["Autonomic division (visceral nervous system)", "Smooth muscle, cardiac muscle, glands, some adipose tissue", "Heart rate speeding up without your deciding it"]]),
     ("ul", ["The autonomic division has two branches that often have opposite effects on the same organ. The organ's activity reflects the balance between them.",
             "Sympathetic branch: fight-or-flight. Prepares the body for stress and effort, for example raising heart rate and sending more blood to working muscles.",
             "Parasympathetic branch: rest-and-digest. Runs maintenance such as digestion, and slows the heart.",
             "Enteric nervous system: a network of neurons in the wall of the digestive tract. It can sense, decide and command on its own, and the autonomic division normally adjusts it."]),
     ("defs", [("Afferent", "Carrying toward the CNS. The sensory division."),
               ("Efferent", "Carrying away from the CNS, toward effectors."),
               ("Effector", "A muscle or gland that carries out a command.")]),
   ]),
   ("Neurons sorted by direction and by shape", [
     ("table", ["By direction", "What it does", "Where"],
      [["Sensory (afferent) neuron", "Carries information toward the CNS", "Receptor to CNS"],
       ["Interneuron", "Connects other neurons; does the processing, comparing and deciding", "Entirely inside the CNS"],
       ["Efferent (motor) neuron", "Carries commands away from the CNS", "CNS to effector"]]),
     ("ul", ["Every neuron has dendrites, short branches that receive signals, and one axon, a long fiber that carries the signal away.",
             "Neurons are sorted by shape by counting the processes that leave the cell body."]),
     ("table", ["Shape", "Processes", "Where it is found"],
      [["Multipolar", "Many dendrites and one axon", "Interneurons of the brain and spinal cord, and efferent neurons such as somatic motor neurons (cell bodies in the ventral horn)"],
       ["Bipolar", "One dendrite and one axon", "Retina and olfactory epithelium"],
       ["Pseudounipolar", "One stalk that splits in two", "Sensory neurons for touch, pain and stretch; cell bodies in the dorsal root ganglia"]]),
     ("ul", ["In a pseudounipolar neuron the signal runs from the skin straight past the cell body toward the spinal cord, without detouring through the cell body where it could fade.",
             "Sensory fibers enter the spinal cord through the dorsal root and motor axons leave through the ventral root, so damage to one root affects one direction only."]),
   ]),
   ("The four working regions of a neuron", [
     ("ol", ["Dendrites receive signals from other cells. One neuron may receive input from thousands of others. The signals here are graded potentials: small, local, variable in size, and they fade as they spread.",
             "The cell body (soma) holds the nucleus and makes the cell's proteins. Signals from every branch spread into it and add together, which is called summation.",
             "The trigger zone, the axon hillock and the initial segment of the axon, decides whether to fire. It has the highest density of voltage-gated sodium channels in the neuron, so it reaches threshold first. In a sensory neuron the trigger zone sits near the receptor endings instead.",
             "The axon carries action potentials. An action potential is all or none: it is rebuilt at full size as it travels, so it arrives as big as it started. A motor axon from the spinal cord to the foot can be about a meter long.",
             "The axon terminals release neurotransmitter. When an action potential arrives, voltage-gated calcium channels open, calcium rushes in, and the rise in calcium makes vesicles fuse with the membrane and release neurotransmitter."]),
     ("ul", ["A stronger stimulus does not make a bigger action potential. It makes action potentials fire more often, and it recruits more neurons.",
             "If the calcium channels at the terminal are blocked, the action potential arrives normally but no neurotransmitter is released, so the message stops at the terminal."]),
     ("defs", [("Graded potential", "A small, local change in membrane voltage whose size varies with the input and which fades with distance."),
               ("Action potential", "A large, all-or-none signal that travels the length of the axon without getting smaller."),
               ("Trigger zone", "The axon hillock and initial segment, where the neuron decides whether to fire."),
               ("Synapse", "The junction between an axon terminal and the next cell: a neuron, a muscle fiber or a gland.")]),
   ]),
   ("The glial cells", [
     ("table", ["Glial cell", "Where", "Job"],
      [["Astrocyte", "CNS", "Most common CNS glia. Controls the fluid around neurons: takes up extra potassium after neurons fire, clears leftover neurotransmitter such as glutamate, passes fuel from blood to neurons. Its end feet signal capillary cells to form the tight junctions of the blood-brain barrier."],
       ["Oligodendrocyte", "CNS", "Makes myelin. One oligodendrocyte wraps segments of several axons."],
       ["Microglia", "CNS", "Resident immune cells. Patrol, then activate to engulf invaders, damaged cells and debris."],
       ["Ependymal cell", "CNS", "Lines the ventricles and central canal. Specialized ependymal cells make cerebrospinal fluid; cilia help move it."],
       ["Schwann cell", "PNS", "Makes myelin. One Schwann cell wraps one segment of one axon. Helps cut peripheral axons regrow."],
       ["Satellite cell", "PNS", "Forms a capsule around cell bodies in ganglia and regulates the fluid around them. A kind of Schwann cell that does not make myelin."]]),
     ("ul", ["Blood-brain barrier: brain capillaries are sealed by tight junctions. Small lipid-soluble molecules (oxygen, carbon dioxide, alcohol) cross easily; water-soluble molecules (glucose, amino acids) need transport proteins. It keeps out many toxins, and many drugs.",
             "If astrocytes cannot clear potassium, outside potassium rises, the resting potential becomes less negative, and neurons sit closer to threshold. This is one link to seizure disorders.",
             "Hydrocephalus: if cerebrospinal fluid cannot drain, it builds up, the ventricles swell and pressure rises on the brain. Fluid stays steady only when production matches drainage.",
             "Because one oligodendrocyte myelinates many axons, losing one damages insulation on many fibers."]),
     ("h3", "When an axon is cut"),
     ("ol", ["The part of the axon cut off from the cell body dies, because it is no longer supplied.",
             "In the PNS, Schwann cells survive, clear debris, line up into a tube and release growth factors, and the axon can regrow along that path, at roughly a millimeter a day.",
             "In the CNS, oligodendrocytes and astrocytes release molecules that block regrowth, and astrocytes form a scar."]),
   ]),
   ("Myelin and what happens when it is lost", [
     ("ul", ["Myelin is a glial cell's own membrane wound around the axon many times. Membrane is mostly lipid and ions cannot cross it, so myelin is electrical insulation.",
             "Myelin covers the axon in segments. The bare gaps between them are the nodes of Ranvier.",
             "Voltage-gated sodium channels are packed at the nodes, with very few in the membrane under the myelin.",
             "The slow step in conduction is the membrane opening channels to rebuild the signal, not current moving along the inside of the axon. Myelin stops current leaking out, so current from one node reaches the next node still strong enough to rebuild the signal there.",
             "The signal is rebuilt only at the nodes, so it effectively jumps from node to node. This is saltatory conduction.",
             "In electrical terms, myelin raises membrane resistance (less current leaks out) and lowers membrane capacitance (less charge is needed to change the voltage). A wider axon also conducts faster, because it has less resistance to current flowing along the inside."]),
     ("table", ["Axon", "Conduction speed"],
      [["Large, myelinated", "Up to about 120 m/s"],
       ["Thin, unmyelinated", "About 0.5 to 2 m/s"]]),
     ("h3", "Demyelination"),
     ("ol", ["The myelin over a stretch of axon is destroyed and the bare axon is exposed.",
             "Current leaks out of the bare stretch.",
             "That membrane was always covered, so it has very few sodium channels to rebuild the signal.",
             "If the stretch is long enough, the signal fades before the next node reaches threshold. The message never arrives: conduction block."]),
     ("table", ["Disease", "Myelin attacked", "Pattern"],
      [["Multiple sclerosis", "CNS myelin, made by oligodendrocytes", "Scattered, unrelated-looking symptoms (vision, sensation, strength, balance) that come and go as patches become inflamed and partly recover. Warmth can briefly tip barely conducting fibers into block."],
       ["Guillain-Barré syndrome", "PNS myelin, made by Schwann cells", "Weakness that climbs the legs, often after an infection; reflexes lost; conduction slowed but response size near normal. Most people recover over weeks to months because Schwann cells remyelinate well."]]),
   ]),
   ("Axonal transport", [
     ("ul", ["Proteins are made in the cell body. Nothing is built at the axon terminals, so everything has to be shipped along the axon.",
             "Cargo travels on microtubules that run the length of the axon. Motor proteins walk along them, splitting ATP at every step. If the microtubules are taken apart, traffic stops in both directions."]),
     ("table", ["Direction", "Motor protein", "Cargo"],
      [["Anterograde: cell body to terminals", "Kinesin", "Synaptic vesicles, new membrane proteins such as channels, mitochondria"],
       ["Retrograde: terminals to cell body", "Dynein", "Worn-out membrane and organelles for recycling, growth factor signals from the target cell"]]),
     ("table", ["Speed", "Rate", "Carries"],
      [["Fast transport", "Up to about 400 mm per day", "Vesicles and mitochondria"],
       ["Slow transport", "About 0.2 to 2.5 mm per day", "Cytoskeleton proteins and dissolved enzymes"]]),
     ("ul", ["At 400 mm per day, fast transport covers a 1 meter axon in about 2.5 days.",
             "A cut peripheral axon regrows about a millimeter a day because it is built from cytoskeleton proteins that arrive by slow transport.",
             "A block on the axon piles outward cargo up on the cell body side. Blocking the inward motor piles returning cargo up on the terminal side.",
             "Retrograde transport is also a way in: rabies virus and tetanus toxin ride it from the terminals into the CNS. Herpes viruses ride it in to hide in a sensory cell body, and later ride anterograde transport back out, so a cold sore returns in the same spot."]),
   ]),
  ]),

 dict(slug="rmp", file="biol005-w04-rmp-walkthrough-notes.html",
  title="The resting membrane potential", walk="biol005-w04-rmp-guided.html",
  comps="Week 4 competencies 1 to 5",
  sections=[
   ("Where the ions are", [
     ("table", ["Ion", "Inside (mM)", "Outside (mM)"],
      [["K+", "150", "5"], ["Na+", "15", "145"], ["Cl" + M, "10", "108"], ["Ca2+", "0.0001", "1"],
       ["Large anions (proteins, ATP)", "Many", "Almost none"]]),
     ("ul", ["Textbooks differ a little in the numbers, but the pattern is the same.",
             "Potassium is the only one of these ions crowded inside. Sodium, chloride and calcium are crowded outside.",
             "The large anions are too big to cross the membrane. They are the negative charge left behind when potassium leaves.",
             "Ions cannot cross the lipid membrane on their own. They need channels, which are proteins built from genes."]),
   ]),
   ("How the inside becomes negative", [
     ("ol", ["The cell has many potassium leak channels, which are always open.",
             "Potassium is crowded inside, so it diffuses out through them.",
             "Each potassium carries a positive charge away and leaves an unmatched negative charge behind, so the inside becomes negative. The charge gathers in a thin layer at the membrane, and only a tiny fraction of the potassium has to leave.",
             "The negative inside pulls potassium back in. The pull grows as more potassium leaves.",
             "When the pull in equals the push out, potassium moves in and out equally, with no net movement. That voltage is potassium's equilibrium potential, about " + M + "90 mV.",
             "A few sodium leak channels let a little sodium in, carrying positive charge in and making the inside a bit less negative. Rest settles at about " + M + "70 mV."]),
     ("ul", ["The ion with the most open channels has the most say over the voltage. At rest a neuron is roughly 25 times more permeable to potassium than to sodium.",
             "If the potassium leak channels were blocked, the inside would become less negative. The potassium leak is the main reason the inside is negative at all."]),
     ("defs", [("Resting membrane potential", "The voltage across the membrane of a cell at rest, inside compared with outside, about " + M + "70 mV in a neuron."),
               ("Concentration gradient", "The push on an ion from crowding. It ignores charge."),
               ("Electrical gradient", "The push on an ion from charge. It ignores crowding."),
               ("Electrochemical gradient", "The two pushes added together."),
               ("Equilibrium potential", "The voltage at which the electrical push on an ion exactly balances its concentration push, so it has no net movement. Also called its balance point.")]),
   ]),
   ("The two pushes on each ion", [
     ("table", ["Ion", "Concentration push", "Electrical push at " + M + "70 mV", "Result"],
      [["K+", "Out", "In", "They oppose; a small net push out"],
       ["Na+", "In", "In", "Both point in; sodium is pushed in hard"]]),
     ("table", ["Ion", "Equilibrium potential (about)"],
      [["K+", M + "90 mV"], ["Na+", "+60 mV"], ["Cl" + M, M + "65 mV"], ["Ca2+", "+120 mV"]]),
     ("ul", ["At " + M + "70 mV, potassium is 20 mV from its equilibrium potential and sodium is 130 mV from its. That is why sodium's push is so much stronger."]),
   ]),
   ("The rule for which way an ion moves", [
     ("ul", ["If an ion's channel is open, the ion moves toward its own equilibrium potential and drags the membrane with it.",
             "If the channel is closed, nothing moves, however strong the push.",
             "At rest, open sodium channels let sodium in and the membrane moves up toward +60 mV.",
             "At +30 mV, potassium is 120 mV from its equilibrium potential, so it rushes out and pulls the membrane back down. This is how a cell recovers after an action potential."]),
   ]),
   ("The Nernst and Goldman equations, in plain words", [
     ("ul", ["You read these equations; you do not calculate with them in this course.",
             "The Nernst equation turns one ion's concentration difference into its equilibrium potential. Potassium at 150 mM inside and 5 mM outside gives about " + M + "90 mV.",
             "If outside potassium rises from 5 to 10 mM, potassium's equilibrium potential becomes less negative, about " + M + "72 mV, because the push out is weaker.",
             "The Goldman equation is the tug of war written as math: a weighted average of the equilibrium potentials, where each ion's weight is how permeable the membrane is to it.",
             "Potassium's weight is biggest, so rest sits near " + M + "90 mV; sodium's small weight pulls it to about " + M + "70 mV.",
             "More open potassium channels move rest closer to " + M + "90 mV (hyperpolarization). Many open sodium channels swing the membrane toward +60 mV, which is how an action potential begins."]),
   ]),
   ("The sodium-potassium pump", [
     ("ul", ["The Na+/K+ ATPase uses ATP to move 3 Na+ out and 2 K+ in each cycle, carrying both ions against their gradients.",
             "Its main job is to keep the concentration gradients in place over minutes to hours, because the leaks never stop.",
             "Because it moves 3 positive charges out for every 2 in, it adds a few millivolts of negative charge directly.",
             "It does not set " + M + "70 mV from moment to moment; the leak channels do that. If the pump stops, the voltage barely changes at first, then drifts toward 0 mV over hours as the gradients run down. The pump is not the battery. It keeps the battery charged."]),
   ]),
   ("Words for changes in membrane potential", [
     ("defs", [("Depolarization", "The membrane becomes less negative than rest (moves toward zero or above)."),
               ("Overshoot", "The part of an action potential where the inside is positive."),
               ("Repolarization", "The membrane moves back toward its resting value, even while the inside is still positive."),
               ("Hyperpolarization", "The membrane becomes more negative than rest.")]),
     ("ul", ["The words describe which way the voltage moved compared with rest, not whether the inside is positive or negative.",
             "Channels come in four kinds by what opens them: leak (always open), voltage-gated, ligand-gated (chemically gated) and mechanically gated. The channel gating walkthrough builds these in detail."]),
   ]),
   ("Excitability and blood potassium", [
     ("ul", ["A neuron fires when its membrane reaches threshold, about " + M + "55 mV. The gap between rest and threshold is how big a push it needs. That is excitability.",
             "A cell closer to threshold is usually more excitable. If a cell stays depolarized for a long time, its sodium channels stay inactivated and it becomes less excitable."]),
     ("table", ["Condition", "Blood K+ (normal 3.5 to 5.0 mM)", "K+ equilibrium potential", "Resting potential", "Effect"],
      [["Hyperkalemia (missed dialysis)", "7.0 mM", "About " + M + "81 mV", "About " + M + "65 mV, depolarized", "At first closer to threshold; if it lasts, sodium channels stay inactivated and cells barely fire. In the heart: slow, disorganized conduction and risk of cardiac arrest."],
       ["Hypokalemia (loop diuretic)", "2.8 mM", "About " + M + "105 mV", "About " + M + "76 mV, hyperpolarized", "Farther from threshold, so muscles are weak; cramps. Low potassium also makes digoxin toxicity more likely."]]),
     ("ul", ["Treating hyperkalemia: IV calcium gluconate protects the heart by raising the threshold of heart cells, without changing potassium. Insulin with glucose moves potassium into cells by speeding the pump, which lasts only hours. Dialysis is the only one of the three that removes the potassium.",
             "Lidocaine blocks voltage-gated sodium channels, not the leak channels, so the resting potential barely changes, but no pain signal can be sent. A normal resting potential is necessary for a nerve to work, but it is not enough on its own."]),
   ]),
  ]),

 dict(slug="channel-gating", file="biol005-w04-channel-gating-walkthrough-notes.html",
  title="Ion channel gating", walk="biol005-w04-channel-gating-guided.html",
  comps="",
  sections=[
   ("Leak channels and gated channels", [
     ("ul", ["Leak channels have no gate. They are always open and let through whatever fits, all the time. Potassium leak channels are why a resting cell has a voltage at all.",
             "Most channels are gated: a moving part sits in the pore and blocks it until a specific trigger moves it.",
             "Gates let the cell control when ions move, not just whether they can. Leak channels set the resting voltage; gated channels let the cell act at a chosen moment."]),
     ("defs", [("Leak channel", "A channel with no gate, open all the time."),
               ("Gated channel", "A channel with a gate that opens only in response to a specific trigger.")]),
   ]),
   ("What opens a gate", [
     ("table", ["Channel", "Opens when", "Where you meet it"],
      [["Voltage-gated", "The voltage across the membrane changes. Charged parts of the channel sit in the electric field and physically move, and the gate moves with them.", "The sodium and potassium channels of axons; calcium channels in axon terminals"],
       ["Ligand-gated (chemically gated)", "A specific molecule binds to a receptor site on the channel, like a key in a lock. The gate stays open while it is bound.", "Acetylcholine receptors where a motor neuron meets a muscle fiber"],
       ["Mechanically gated", "The membrane is stretched, bent or pressed.", "Sensory endings in the skin, hair cells of the inner ear, walls of blood vessels"]]),
     ("ul", ["Positive feedback in voltage-gated sodium channels: channels open when the membrane becomes less negative, sodium comes in and makes it less negative still, which opens more channels. This runaway loop is why an action potential goes all the way once it starts.",
             "Ligand-gated channels are how one cell talks to the next: the message crosses the gap as a chemical, and the chemical opens gates on the far side.",
             "A drug that sits in the acetylcholine binding sites without opening the channels leaves the channels shut, and the muscle is not told to contract: weakness or paralysis. Some paralytic drugs used in surgery work this way. In myasthenia gravis, antibodies destroy these receptors, causing weakness that worsens with use.",
             "Mechanically gated channels are where sensation begins: pressure, sound vibration and stretch are turned into an electrical signal."]),
   ]),
   ("The voltage-gated sodium channel has two gates", [
     ("ul", ["Activation gate: at the outer end of the pore. Closed at rest; opens quickly at threshold.",
             "Inactivation gate: at the inner end of the pore. Open at rest; responds to the same voltage change but moves slowly, and then plugs the pore from the inside.",
             "Both gates must be out of the way for sodium to pass."]),
     ("table", ["State", "Activation gate (outer)", "Inactivation gate (inner)", "Na+ passes?", "Can it open now?"],
      [["Resting", "Closed", "Open", "No", "Yes, it is ready"],
       ["Open", "Open", "Open", "Yes, sodium floods in", "It is open"],
       ["Inactivated", "Open", "Closed, plugging the pore", "No", "No, whatever the stimulus"]]),
     ("h3", "The sequence, every time the channel fires"),
     ("ol", ["At rest (about " + M + "70 mV) the channel is in the resting state.",
             "The membrane depolarizes to threshold, about " + M + "55 mV, and the activation gate swings open.",
             "Sodium pours in, driven by both its concentration gradient and the negative inside, so the voltage shoots up. This is the upstroke of the action potential.",
             "About a millisecond later the slow inactivation gate closes and plugs the pore. Sodium stops, on its own, with nothing needed to switch it off.",
             "The membrane repolarizes toward rest.",
             "Only then does the channel reset: the activation gate closes, then the inactivation gate swings back out of the pore. The channel is back in the resting state."]),
     ("defs", [("Inactivation", "The inner gate blocking the pore while the outer gate is still open. Different from being closed: a closed channel can open, an inactivated channel cannot."),
               ("Absolute refractory period", "The time after firing when most sodium channels are inactivated, so no stimulus, however strong, can produce another action potential. It sets the top firing rate and keeps an action potential traveling in one direction."),
               ("Channel reset", "Return from inactivated to resting, which happens only when the membrane repolarizes.")]),
   ]),
   ("The voltage-gated potassium channel", [
     ("ul", ["It responds to the same depolarization as the sodium channel, but it has only one gate and it is slow.",
             "It is still opening while sodium channels are inactivating, so potassium leaves and helps bring the membrane back down.",
             "It closes late too, so potassium keeps leaving after the voltage is back at rest. The voltage dips below rest until the channels close.",
             "After-hyperpolarization: that dip below rest. It is part of why a neuron is harder to fire for a short time after an action potential, since the membrane is further from threshold."]),
   ]),
   ("Reading patients with the channel states", [
     ("table", ["Patient", "What is wrong", "Why"],
      [["Local anesthetic (lidocaine) at the dentist", "Numb, but still able to move the face", "Lidocaine sits in the sodium channel pore, so sodium cannot enter even when the activation gate opens. No action potential, no pain signal. It binds best to open or inactivated channels, so it acts fastest on nerves firing often, and small pain fibers are blocked before larger motor fibers."],
       ["Severe hyperkalemia", "Excitable tissue stops responding; life threatening in the heart", "High outside potassium holds the membrane depolarized, so sodium channels stay inactivated and never reset."],
       ["Hyperkalemic periodic paralysis", "Episodes of weakness with high blood potassium, normal between episodes", "An inherited muscle sodium channel that is slow to inactivate keeps the membrane depolarized; channels stay inactivated, so the muscle cannot fire. Too much depolarization means no activity, not more."]]),
   ]),
  ]),

 dict(slug="graded-potentials", file="biol005-w04-graded-potentials-walkthrough-notes.html",
  title="Graded potentials", walk="biol005-w04-graded-potentials-guided.html",
  comps="Week 4 competencies 12 and 14",
  sections=[
   ("Two kinds of electrical signal", [
     ("table", ["", "Graded potential", "Action potential"],
      [["Where", "Input zone: dendrites and cell body", "Starts at the trigger zone, travels the axon"],
       ["Size", "Varies with the stimulus", "Always the same size (all or none)"],
       ["Distance", "Short; fades as it spreads", "Long; does not fade"],
       ["Threshold", "None", "Fires only if the trigger zone reaches threshold"],
       ["Channels", "Chemically or mechanically gated", "Voltage-gated sodium and potassium"]]),
   ]),
   ("How a graded potential is made", [
     ("ol", ["A stimulus opens gated channels: a neurotransmitter opens ligand-gated channels at a synapse, or stretch opens mechanically gated channels in a sensory ending.",
             "Ions cross, and the membrane moves toward the equilibrium potential of the ion whose permeability went up.",
             "Sodium in: the inside becomes less negative, a depolarizing graded potential.",
             "Potassium out: the inside becomes more negative, a hyperpolarizing graded potential, which moves the cell away from firing.",
             "The channels close and the membrane returns to rest. A graded potential lasts from a few milliseconds to tens of milliseconds."]),
     ("ul", ["A stronger stimulus opens more channels or holds them open longer, so more ions cross and the change is larger. That is what graded means.",
             "Example sizes recorded at one spot: weak stimulus 3 mV, medium 7 mV, strong 12 mV; a potassium-opening stimulus 8 mV below rest."]),
   ]),
   ("Why a graded potential fades as it spreads", [
     ("ul", ["Local current flow: the positive charge that enters spreads along the inside of the dendrite in both directions.",
             "Current leak: some of that charge escapes through the open leak channels along the membrane, like water from a leaky hose.",
             "Cytoplasmic resistance: the cytoplasm resists the flow of charge, the way a thin wire resists current more than a thick one.",
             "Together they make the change smaller at every point farther from the channels that opened. Example: 20 mV at point 1 next to the channels, then 12, 7 and 4 mV at points farther along.",
             "A wider dendrite has lower cytoplasmic resistance, so a graded potential spreads farther. Current leak does not change, because it depends on the leak channels in the membrane."]),
     ("defs", [("Local current flow", "Spread of charge through the cytoplasm away from where ions entered."),
               ("Current leak", "Loss of charge across the membrane through open leak channels."),
               ("Cytoplasmic resistance", "The cytoplasm's resistance to the flow of charge; lower in a wider process.")]),
   ]),
   ("What reaches the trigger zone", [
     ("ul", ["The trigger zone fires only if the membrane there reaches threshold, about " + M + "55 mV. From rest at " + M + "70 mV that takes about 15 mV of depolarization.",
             "What counts is the size of the graded potential when it arrives, not where it started.",
             "Graded potentials that overlap in time add together: summation. Depolarizing ones add; hyperpolarizing ones subtract.",
             "Real graded potentials that overlap add to a little less than their plain sum. The reasoning is the same."]),
     ("table", ["Inputs reaching the trigger zone", "Arithmetic", "Voltage", "Result"],
      [["One excitatory, 8 mV", M + "70 + 8", M + "62 mV", "Subthreshold, no action potential"],
       ["Two excitatory together, 8 mV each", M + "70 + 16", M + "54 mV", "Suprathreshold, fires"],
       ["Two excitatory plus one inhibitory of 5 mV", M + "70 + 8 + 8 " + M + " 5", M + "59 mV", "Subthreshold, no action potential"]]),
     ("defs", [("Threshold", "The voltage at the trigger zone, about " + M + "55 mV, at which an action potential fires."),
               ("Subthreshold", "A graded potential too small to bring the trigger zone to threshold."),
               ("Suprathreshold", "A graded potential large enough to bring the trigger zone to threshold."),
               ("Summation", "The adding together of graded potentials that overlap in time.")]),
   ]),
   ("Patient: the pufferfish meal", [
     ("ul", ["Tetrodotoxin plugs voltage-gated sodium channels from the outside. It does not block chemically or mechanically gated channels.",
             "His resting potential is normal (" + M + "70 mV). Weak stimuli still make small graded potentials, about 5 mV, that fade.",
             "A strong stimulus makes about 20 mV, which goes past threshold, but no action potential appears, because the channels that make the action potential are plugged.",
             "His neurons can still take in signals but cannot send them down an axon. The action potential walkthrough finishes this case."]),
   ]),
  ]),
 dict(slug="action-potential", file="biol005-w04-action-potential-walkthrough-notes.html",
  title="The action potential", walk="biol005-w04-action-potential-guided.html",
  comps="Week 4 competencies 13 to 16",
  sections=[
   ("The key numbers", [
     ("table", ["Point", "Voltage", "What sets it"],
      [["Rest", M + "70 mV", "Mostly potassium leak (resting potential walkthrough)"],
       ["Threshold", "about " + M + "55 mV", "Sodium current in first outweighs potassium current out"],
       ["Peak", "about +30 mV", "Sodium inactivation gates close and potassium channels open"],
       ["After-hyperpolarization", "about " + M + "80 mV", "Potassium channels slow to close"],
       ["Sodium's balance point", "+60 mV", "The ceiling the rise heads toward"],
       ["Potassium's balance point", M + "90 mV", "The floor the dip heads toward"]]),
     ("p", "The whole spike, from threshold back to rest, lasts a few milliseconds. The rise and the fall together take about 1 to 2 ms."),
   ]),
   ("The two voltage-gated channels", [
     ("table", ["Channel", "Gates", "At rest", "When depolarized"],
      [["Voltage-gated Na+ channel", "Activation gate (outside), inactivation gate (inside)", "Activation closed, inactivation open", "Activation opens fast; inactivation closes a little later and stays closed until the membrane repolarizes"],
       ["Voltage-gated K+ channel", "One gate", "Closed", "Opens slowly, at about the time sodium channels inactivate, and closes slowly"]]),
     ("ul", ["Both channels are opened by depolarization. The difference that shapes the action potential is timing: sodium is fast, potassium is slow.",
             "A stimulus can open an activation gate. Nothing can force an inactivation gate open. It reopens only after the membrane repolarizes."]),
   ]),
   ("Reaching threshold", [
     ("ul", ["A graded potential depolarizes the trigger zone and opens some voltage-gated sodium channels.",
             "Below threshold (example: a 10 mV push to " + M + "60 mV) the sodium coming in is less than the potassium leaking out. The membrane falls back to rest. Nothing fires.",
             "At threshold (a 15 mV push to about " + M + "55 mV) the sodium current in matches, then outweighs, the potassium current out.",
             "Threshold is a balance of two currents, not a fixed number."]),
     ("ol", ["Sodium comes in and the membrane depolarizes.",
             "Depolarization opens more voltage-gated sodium channels.",
             "More sodium comes in, and the membrane depolarizes further.",
             "Back to step 2. This self-feeding loop is positive feedback, and once it starts the stimulus no longer matters."]),
   ]),
   ("The phases, in order", [
     ("table", ["Phase", "Voltage", "Na+ channels", "K+ channels", "Ion movement"],
      [["Rest", M + "70 mV", "Closed (activation gate closed)", "Closed", "Leak only"],
       ["Rising phase (depolarization)", M + "55 to about +30 mV", "Open", "Starting to open", "Na+ rushes in"],
       ["Peak (overshoot above 0 mV)", "about +30 mV", "Inactivation gates close", "Open", "Na+ stops; K+ starts to leave"],
       ["Falling phase (repolarization)", "+30 back to " + M + "70 mV", "Inactivated", "Open", "K+ flows out"],
       ["After-hyperpolarization", "down to about " + M + "80 mV, then back to rest", "Resetting: activation closes, inactivation opens", "Still open, closing slowly", "Extra K+ out moves the membrane toward " + M + "90 mV"]]),
     ("ul", ["The rise heads toward sodium's balance point (+60 mV) because the membrane is now most permeable to sodium, the same rule as the resting potential.",
             "It stops near +30 mV because the sodium inactivation gates close and the potassium channels open.",
             "Potassium leaving brings the voltage down. The sodium-potassium pump does not.",
             "The dip below rest happens because the potassium channels are slow to close, so the membrane is briefly more permeable to potassium than at rest."]),
     ("defs", [("Threshold", "The voltage at which sodium current in first outweighs potassium current out and the action potential takes off; about " + M + "55 mV here."),
               ("Positive feedback", "A loop in which the result of a step makes the step happen more: depolarization opens sodium channels, which cause more depolarization."),
               ("Rising phase (depolarization)", "The fast climb from threshold to the peak, carried by sodium coming in."),
               ("Overshoot", "The part of the action potential above 0 mV, when the inside is positive."),
               ("Falling phase (repolarization)", "The fall from the peak back toward rest, carried by potassium going out."),
               ("After-hyperpolarization", "The brief dip below rest after the spike, caused by potassium channels that are slow to close.")]),
   ]),
   ("How many ions move", [
     ("ul", ["Only a tiny fraction of the ions cross in one action potential. Inside the cell, sodium stays about 15 mM and potassium about 150 mM.",
             "The gradients are still there after a spike, so a neuron can fire again right away without waiting for the pump.",
             "The pump keeps concentrations steady over the long run, across thousands of action potentials. It does not repolarize the membrane after each spike."]),
   ]),
   ("All or none", [
     ("ul", ["Below threshold: no action potential at all. At or above threshold: a full-sized one.",
             "Example: pushes of 5 and 10 mV stay below threshold. Pushes of 16 and 30 mV both give action potentials that peak at about +30 mV.",
             "The size is set by the channels and sodium's balance point, not by the stimulus. A bigger push only reaches threshold a little sooner."]),
     ("defs", [("All or none", "An action potential either happens at full size or does not happen; its size does not depend on the size of the stimulus.")]),
   ]),
   ("Coding stimulus strength", [
     ("ul", ["Because every spike is the same size, size cannot carry information.",
             "Frequency coding: a stronger stimulus makes a single neuron fire more often. A bigger graded potential reaches threshold again sooner after each spike. Example in the walkthrough: 2, 5 and 9 action potentials in the same time for weak, medium and strong.",
             "Population coding: a stronger stimulus activates more receptors, so more neurons fire. Example: 1, 2 and 4 neurons.",
             "A single axon can only use frequency coding."]),
     ("defs", [("Frequency coding", "Signaling stimulus strength by how often a neuron fires."),
               ("Population coding", "Signaling stimulus strength by how many neurons fire.")]),
   ]),
   ("Refractory periods", [
     ("table", ["Period", "When", "Channel state", "Can a second action potential start?"],
      [["Absolute refractory period", "From the start of the spike until the sodium channels begin to reset, through most of the fall", "Na+ inactivation gates closed", "No, no matter how strong the stimulus"],
       ["Relative refractory period", "During the dip below rest", "Some Na+ channels reset; extra K+ channels still open", "Yes, but it takes a stronger stimulus than usual, and the second spike is often a little smaller"]]),
     ("ul", ["Example: during the dip the membrane is near " + M + "78 mV. The same 16 mV push that fired the first spike reaches only " + M + "62 mV, short of threshold.",
             "The absolute refractory period lasts about 1 to 2 ms, which sets a ceiling on firing rate: 1,000 ms " + DIV + " 2 ms = 500 per second, or 1,000 ms " + DIV + " 1 ms = 1,000 per second. Most neurons fire well below this.",
             "The refractory period also keeps the action potential traveling in one direction along the axon (conduction walkthrough)."]),
     ("defs", [("Absolute refractory period", "The time during which no stimulus of any size can start a second action potential, because the sodium inactivation gates are closed."),
               ("Relative refractory period", "The time right after, during which a second action potential can start but only with a stronger stimulus than usual.")]),
   ]),
   ("Patient: a drug that blocks potassium channels", [
     ("ul", ["Dalfampridine blocks voltage-gated potassium channels. It is used to help people with multiple sclerosis walk.",
             "In multiple sclerosis, axons lose myelin, which exposes potassium channels that are normally covered.",
             "With the potassium channels blocked, the rise and peak barely change, the fall is much slower, and the dip below rest mostly disappears. The action potential gets wider.",
             "A wider action potential delivers more charge to the next stretch of axon, which helps the signal cross a stretch that has lost its myelin.",
             "Blocking these channels throughout the brain can make neurons fire too easily, so the dose is kept low: too much can cause seizures."]),
   ]),
  ]),
]
