"""
tools/walkthrough_notes_w05.py

The written notes that go with each Week 5 guided walkthrough. Oct 4 2026.
Same rules as tools/walkthrough_notes_w04.py: real notes in bullets,
definitions, sequences and tables, not a copy of the steps, and nothing here
that is not taught in the walkthrough itself.

Block types:  ("p", text)  ("ul", [..])  ("ol", [..])  ("defs", [(term, def)])
              ("table", [header], [[row]...])  ("h3", text)
Run: python3 tools/make_walkthrough_notes_w05.py
"""
M = "\u2212"

NOTES = [
 dict(slug="reflexes", file="biol005-w05-reflexes-walkthrough-notes.html",
  title="Spinal reflexes", walk="biol005-w05-reflexes-guided.html",
  comps="Week 5 competencies 1 to 4 and 7",
  sections=[
   ("The reflex arc", [
     ("p", "A reflex is an automatic, stereotyped response to a stimulus. Spinal reflexes are integrated in the spinal cord and do not need the brain."),
     ("ol", ["Receptor: detects the stimulus (for the knee jerk, the muscle spindle).",
             "Sensory (afferent) neuron: carries the signal into the cord through the dorsal root. Its cell body is in the dorsal root ganglion.",
             "Integrating center: the spinal cord gray matter, where the sensory neuron synapses.",
             "Motor (efferent) neuron: carries the response out of the cord through the ventral root.",
             "Effector: the muscle or gland that responds (for the knee jerk, the quadriceps)."]),
     ("defs", [("Monosynaptic reflex", "The sensory neuron synapses directly on the motor neuron: one synapse. Fastest possible reflex. The stretch reflex is the example."),
               ("Polysynaptic reflex", "One or more interneurons between the sensory and motor neuron. Slower, because each synapse adds a delay of roughly half a millisecond, but able to inhibit, to cross the midline, and to reach several segments.")]),
     ("table", ["Cut", "Reflex", "Sensation from that area", "Voluntary movement"],
      [["Dorsal root", "Lost", "Lost", "Intact"],
       ["Ventral root", "Lost", "Intact", "Lost"]]),
   ]),
   ("Kinds of reflexes", [
     ("table", ["Sorted by", "Kinds", "Example"],
      [["Effector", "Somatic motor (skeletal muscle) or autonomic (smooth muscle, cardiac muscle, glands)", "Knee jerk; baroreceptor reflex"],
       ["Integrating center", "Spinal (spinal cord) or cranial (brain)", "Knee jerk; pupillary light reflex (midbrain)"],
       ["Learned or not", "Innate (present from birth) or learned (acquired with experience)", "Withdrawal reflex; salivating at the smell of a favorite food"],
       ["Synapses", "Monosynaptic or polysynaptic", "Stretch reflex; withdrawal reflex"]]),
     ("p", "The pupillary light reflex is autonomic, cranial, innate and polysynaptic."),
   ]),
   ("The stretch reflex", [
     ("ul", ["The muscle spindle is a capsule of small intrafusal muscle fibers lying in parallel with the ordinary extrafusal fibers. Sensory endings wrap around the middle of the intrafusal fibers.",
             "Spindles report muscle length. They fire tonically even at rest, because the spindle is slightly stretched.",
             "Stretch the muscle: mechanically gated channels in the sensory endings open, the spindle afferent fires faster, and it excites the alpha motor neurons of the same muscle, which contracts. This is negative feedback on muscle length.",
             "Reciprocal inhibition: a branch of the spindle afferent excites an inhibitory interneuron, which inhibits the motor neurons of the antagonist, so the antagonist relaxes. Inhibition always needs an interneuron, because a sensory neuron's transmitter is excitatory.",
             "Alpha-gamma coactivation: gamma motor neurons contract the ends of the intrafusal fibers during a contraction, keeping the spindle taut so it keeps reporting length. Without them the spindle would go slack and silent."]),
     ("defs", [("Muscle spindle", "Stretch receptor in parallel with the muscle fibers. Reports length."),
               ("Alpha motor neuron", "Motor neuron to the extrafusal fibers that do the work."),
               ("Gamma motor neuron", "Motor neuron to the ends of the intrafusal fibers of the spindle.")]),
   ]),
   ("The Golgi tendon organ", [
     ("ul", ["Collagen fibers at the junction of muscle and tendon with a sensory ending threaded between them. It lies in series with the muscle fibers.",
             "It reports tension (force). When the muscle pulls on the tendon, the collagen squeezes the ending and it fires.",
             "Its reflex inhibits the same muscle through an inhibitory interneuron, reducing force. It helps protect muscle and tendon from damaging loads and can make a muscle give way under an extreme load."]),
     ("table", ["", "Muscle spindle", "Golgi tendon organ"],
      [["Position", "In parallel with the muscle fibers", "In series, at the tendon"],
       ["Reports", "Length (stretch)", "Tension (force)"],
       ["Reflex effect on its own muscle", "Excites: contract", "Inhibits: relax"],
       ["Synapses", "Monosynaptic to its own muscle", "Polysynaptic, through an inhibitory interneuron"],
       ["Held still while the load rises", "Steady firing", "Firing rises"]]),
   ]),
   ("Withdrawal and crossed extensor reflexes", [
     ("ol", ["Nociceptors in the right foot fire (stepping on a tack).",
             "Sensory neurons enter the cord and excite interneurons.",
             "Same side: excitatory interneurons drive the flexor motor neurons, and inhibitory interneurons quiet the extensor motor neurons. The foot lifts. This is the flexion (withdrawal) reflex.",
             "Other side: interneurons cross the midline. The left extensors contract and the left flexors are inhibited, so the left leg takes the body's weight. This is the crossed extensor reflex.",
             "Interneurons also spread the signal up and down several segments, so the hip, knee and ankle move together."]),
     ("ul", ["Both reflexes are polysynaptic: inhibition, crossing and spreading all need interneurons.",
             "Without the crossed extensor half, the injured foot would still lift but the other leg would buckle under the load."]),
   ]),
   ("The brain's control of spinal reflexes", [
     ("ul", ["Muscle tone: spindles fire at rest, keeping a few alpha motor neurons active, so a resting muscle is slightly firm. Cutting the dorsal roots removes tone and the tendon reflex.",
             "Descending pathways from the brain act on spinal motor neurons, interneurons and gamma motor neurons, and on balance they hold spinal reflexes in check.",
             "Jendrassik maneuver: pulling the hooked hands apart during the tap is thought to raise descending drive and spindle sensitivity, so a weak reflex gets bigger. A reflex that reinforces has an intact arc.",
             "Plantar response: stroking the sole normally curls the toes down. A big toe that extends with the toes fanning is the Babinski sign, an upper motor neuron sign. It is normal in infants until about one to two years old, while the corticospinal tract matures."]),
     ("table", ["", "Upper motor neuron lesion", "Lower motor neuron lesion"],
      [["Where", "Motor pathway in the brain or cord above the reflex (corticospinal tract)", "Ventral horn motor neuron, ventral root or peripheral nerve"],
       ["Strength", "Weak", "Weak"],
       ["Tone", "High (spasticity)", "Low (flaccid)"],
       ["Reflexes", "Brisk, often with clonus", "Reduced or absent"],
       ["Plantar response", "Babinski sign", "Normal or absent"],
       ["Over weeks", "Little wasting", "Muscle wasting and fasciculations"]]),
   ]),
   ("Testing reflexes", [
     ("table", ["Grade", "Meaning"],
      [["0", "Absent"], ["1+", "Less than usual"], ["2+", "Normal"], ["3+", "Brisker than usual"], ["4+", "Very brisk, often with clonus"]]),
     ("ul", ["An absent reflex means the arc is broken somewhere: receptor, sensory neuron or dorsal root, cord segment, motor neuron or ventral root, or muscle (a lower motor neuron or sensory problem).",
             "A very brisk reflex with clonus usually means the descending pathways from the brain that normally hold reflexes in check are damaged (an upper motor neuron lesion).",
             "Compare left with right. A difference between sides matters more than one number.",
             "Latency separates a reflex from a voluntary response. The knee jerk appears a few tens of milliseconds after the tap. Catching a dropped ruler takes about 150 to 250 milliseconds, because the path runs through the eyes, the brain and down the cord, crossing many more synapses."]),
   ]),
  ]),

 dict(slug="sensory-coding", file="biol005-w05-sensory-coding-walkthrough-notes.html",
  title="Sensory receptors and coding", walk="biol005-w05-sensory-coding-guided.html",
  comps="Week 5 competencies 8 to 12",
  sections=[
   ("Transduction", [
     ("ol", ["A stimulus opens channels in the receptor membrane (for touch, mechanically gated cation channels).",
             "Sodium enters and the ending depolarizes: a receptor potential. It is a graded potential: bigger for a stronger stimulus, fading as it spreads.",
             "If the receptor potential is still above threshold at the trigger zone, the trigger zone fires action potentials.",
             "The action potentials are all the same size and travel unchanged along the axon. At the trigger zone, information carried by size becomes information carried by frequency."]),
     ("defs", [("Sensory transduction", "Converting the energy of a stimulus into a change in membrane potential."),
               ("Receptor potential", "The graded potential produced in a sensory receptor by a stimulus."),
               ("Frequency coding", "A stronger stimulus produces a larger receptor potential and a higher firing frequency."),
               ("Population coding", "A stronger stimulus also reaches the thresholds of more receptors, so more sensory neurons fire.")]),
   ]),
   ("Receptor classes", [
     ("table", ["Class", "Stimulus", "Example locations"],
      [["Mechanoreceptor", "Pressure, stretch, vibration, sound", "Skin, muscle spindles, baroreceptors in the carotid arteries, hair cells of the ear"],
       ["Chemoreceptor", "Particular molecules", "Carotid body (blood O2, CO2, pH), taste buds, olfactory epithelium"],
       ["Thermoreceptor", "Temperature", "Skin, hypothalamus"],
       ["Photoreceptor", "Light", "Retina (rods and cones)"],
       ["Nociceptor", "Stimuli strong enough to damage tissue", "Skin, joints, muscles, internal organs"]]),
     ("p", "Most receptors are inside the body, reporting on conditions you are not aware of."),
   ]),
   ("What the brain is told", [
     ("table", ["Property", "How it is coded"],
      [["Modality (which sense)", "Labeled line: which pathway is active and where it ends in the cortex"],
       ["Location", "Which sensory neurons fire, set by their receptive fields; sharpened by lateral inhibition"],
       ["Intensity", "Firing frequency, and the number of receptors firing"],
       ["Duration", "How long the firing lasts, which depends on adaptation"]]),
     ("ul", ["Labeled line: pressure on a closed eye is seen as light, because the signal arrives in the visual cortex.",
             "Law of projection: stimulating a sensory nerve anywhere along its length produces a sensation that seems to come from the receptors at its end. Phantom limb pain is an example."]),
   ]),
   ("Receptive fields and acuity", [
     ("ul", ["A receptive field is the area that changes one sensory neuron's firing when stimulated.",
             "Small, dense receptive fields (fingertips, lips) give fine acuity and two-point thresholds of a few millimeters. Large, sparse fields (the back) give thresholds of several centimeters.",
             "Two points are felt as two when they stimulate different receptive fields with an unstimulated field between them.",
             "Lateral inhibition: a strongly stimulated neuron inhibits its neighbors through interneurons, increasing the contrast between center and edge so the stimulus is located more precisely."]),
   ]),
   ("Adaptation", [
     ("table", ["", "Tonic (slowly adapting)", "Phasic (rapidly adapting)"],
      [["Response to a steady stimulus", "Keeps firing, slowing a little", "Fires at onset, falls silent, often fires again at offset"],
       ["Reports", "The stimulus, continuously", "Change"],
       ["Examples", "Muscle spindles, baroreceptors, nociceptors", "Pacinian corpuscles (vibration), hair follicle receptors"]]),
     ("p", "Each receptor's adaptation matches its job. Monitoring blood pressure with a phasic receptor would leave a sustained drop unreported after its first moment."),
   ]),
  ]),

 dict(slug="pathways-pain", file="biol005-w05-pathways-pain-walkthrough-notes.html",
  title="Spinal pathways, touch and pain", walk="biol005-w05-pathways-pain-guided.html",
  comps="Week 5 competencies 5, 13 and 14",
  sections=[
   ("Inside the spinal cord", [
     ("ul", ["Gray matter, in the center, shaped like a butterfly: cell bodies, dendrites and synapses.",
             "Dorsal horn: receives sensory input. Ventral horn: cell bodies of somatic motor neurons. Lateral horn, in the thoracic and upper lumbar cord: autonomic neurons.",
             "White matter, around the gray: myelinated axons in tracts, grouped into dorsal, lateral and ventral columns.",
             "Dorsal root: sensory axons in. Its swelling, the dorsal root ganglion, holds the sensory cell bodies. Ventral root: motor axons out.",
             "The two roots join into one spinal nerve, which carries both. There are 31 pairs.",
             "Damage to a dorsal root ganglion (shingles) affects sensation in one strip of skin. Damage to the ventral horn (polio) causes weakness with sensation spared."]),
   ]),
   ("Three long pathways", [
     ("table", ["Tract", "Carries", "Direction", "Where it crosses the midline", "First synapse"],
      [["Dorsal column", "Fine touch, vibration, proprioception", "Up", "Medulla", "Medulla (dorsal column nuclei)"],
       ["Spinothalamic", "Pain, temperature", "Up", "Spinal cord, within a segment or two of entry", "Dorsal horn of the cord"],
       ["Corticospinal", "Voluntary movement", "Down", "Bottom of the medulla (the pyramids)", "Ventral horn motor neuron"]]),
     ("ul", ["Both sensory pathways relay in the thalamus before reaching the somatosensory cortex.",
             "Corticospinal neurons in the cortex are upper motor neurons; the motor neurons in the ventral horn are lower motor neurons.",
             "Each side of the brain senses and moves the opposite side of the body."]),
     ("h3", "Brown-Séquard syndrome: a cut through one half of the cord"),
     ("ul", ["Same side as the cut, below it: loss of fine touch, vibration and position sense, and loss of voluntary movement.",
             "Opposite side, below it: loss of pain and temperature.",
             "The split pattern locates the lesion in the cord. Above the medulla all three pathways have crossed, so a brain lesion takes everything from the same side of the body."]),
   ]),
   ("Touch, from skin to cortex", [
     ("ul", ["Touch ends in the primary somatosensory cortex, the postcentral gyrus, laid out as a map of the body.",
             "The somatosensory homunculus is disproportionate: cortical area matches receptor density and how finely a part discriminates, not its size. Lips and fingertips get the most."]),
   ]),
   ("Pain and its modulation", [
     ("table", ["", "Fast pain", "Slow pain"],
      [["Fiber", "A-delta: thin, myelinated", "C: thinnest, unmyelinated"],
       ["Arrives", "First", "About a second later"],
       ["Feels", "Sharp, prickling, easy to locate", "Dull, aching or burning, hard to locate, lasting"]]),
     ("defs", [("Referred pain", "Pain from an organ felt in the skin. Visceral and somatic afferents converge on the same spinal projection neurons, and the brain assigns the signal to the skin. Heart pain felt in the left arm is the example."),
               ("Gate control theory", "Large touch fibers excite inhibitory interneurons in the dorsal horn that inhibit the pain projection neuron. Rubbing an injury reduces the pain signal."),
               ("Endogenous opioids", "Enkephalins, endorphins and dynorphins. Released by interneurons activated by descending pathways from the brainstem. They act before the synapse, reducing calcium entry and transmitter release (substance P, glutamate) from the nociceptor, and after it, opening potassium channels to hyperpolarize the projection neuron.")]),
   ]),
  ]),

 dict(slug="csf-bbb", file="biol005-w05-csf-bbb-walkthrough-notes.html",
  title="Cerebrospinal fluid and the blood-brain barrier", walk="biol005-w05-csf-bbb-guided.html",
  comps="Week 5 competency 6",
  sections=[
   ("Cerebrospinal fluid", [
     ("ul", ["Fills the ventricles inside the brain and the subarachnoid space around the brain and spinal cord.",
             "Functions: buoyancy (the brain presses on the skull with only a small fraction of its weight), cushioning against sudden movement, and a protected chemical environment."]),
     ("ol", ["Secreted into the ventricles by the choroid plexus, capillaries covered by specialized ependymal cells.",
             "Flows through the ventricles and out into the subarachnoid space.",
             "Reabsorbed into venous blood at the arachnoid villi, which project into the venous sinuses."]),
     ("ul", ["About 150 mL is present at any time; about 500 mL is made each day, so the volume turns over a few times a day.",
             "Blocked outflow: production continues, fluid accumulates, pressure rises within hours. This is hydrocephalus."]),
   ]),
   ("The blood-brain barrier", [
     ("ul", ["Brain capillary endothelial cells are joined by tight junctions that seal the gaps found in most capillaries.",
             "Astrocyte foot processes press on the capillaries and help maintain the tight junctions."]),
     ("table", ["Substance", "Crosses?", "How"],
      [["Oxygen, carbon dioxide", "Yes", "Small and nonpolar: diffuse through the membranes"],
       ["Lipid-soluble drugs (anesthetics, alcohol, nicotine)", "Yes, quickly", "Dissolve through the endothelial membranes"],
       ["Glucose", "Yes", "Carried by GLUT1 transporters, facilitated diffusion"],
       ["Amino acids, L-dopa", "Yes", "Carried by amino acid transporters"],
       ["Large proteins, water-soluble substances with no carrier (dopamine)", "No", "No gaps to pass through and no carrier"]]),
     ("ul", ["Parkinson's disease: dopamine cannot cross, so its precursor L-dopa is given; it crosses on an amino acid carrier and is converted to dopamine in the brain.",
             "Circumventricular organs lack the barrier so neurons can sample the blood: the area postrema detects toxins and triggers vomiting, and parts of the hypothalamus sense blood osmolarity and release hormones into the blood."]),
   ]),
  ]),

 dict(slug="vision", file="biol005-w05-vision-walkthrough-notes.html",
  title="Vision", walk="biol005-w05-vision-guided.html",
  comps="Week 5 competencies 16 to 19",
  sections=[
   ("Focusing light", [
     ("ul", ["Refraction is the bending of light. The cornea does about two thirds of it and has a fixed shape. The lens does the rest and can change shape.",
             "The lens is elastic and held by zonule fibers attached to the ring-shaped ciliary muscle."]),
     ("table", ["", "Far object", "Near object (accommodation)"],
      [["Ciliary muscle", "Relaxed", "Contracted"], ["Zonules", "Taut", "Slack"], ["Lens", "Flat, less bending", "Round, more bending"]]),
     ("defs", [("Pupillary light reflex", "Light in one eye constricts both pupils. In: optic nerve. Center: midbrain. Out: parasympathetic fibers in the oculomotor nerve to the circular muscle of each iris. The response in the unlit eye is the consensual response."),
               ("Afferent defect", "Light in the affected eye constricts neither pupil, light in the other eye constricts both: the problem is in the optic nerve of the affected eye.")]),
   ]),
   ("Refractive errors", [
     ("table", ["Condition", "Cause", "Focus falls", "Blurred", "Corrective lens"],
      [["Myopia (nearsighted)", "Eyeball too long or cornea too curved", "In front of the retina", "Distant objects", "Concave"],
       ["Hyperopia (farsighted)", "Eyeball too short", "Behind the retina", "Near objects", "Convex"],
       ["Presbyopia", "Lens stiffens with age, accommodation fails", "Behind the retina for near objects", "Near objects", "Convex reading lens"],
       ["Astigmatism", "Cornea curved unevenly", "Different for different directions", "Lines in some directions", "Cylindrical"]]),
   ]),
   ("Phototransduction", [
     ("ul", ["Rhodopsin is opsin plus retinal (from vitamin A), in the discs of the rod outer segment.",
             "In the dark: cGMP is high, cGMP-gated cation channels are open, sodium enters, the rod sits near " + M + "40 mV and releases glutamate continuously."]),
     ("ol", ["A photon is absorbed and retinal changes shape.",
             "Rhodopsin is activated.",
             "Rhodopsin activates the G protein transducin.",
             "Transducin activates phosphodiesterase.",
             "Phosphodiesterase breaks down cGMP.",
             "cGMP-gated channels close and sodium entry stops.",
             "The photoreceptor hyperpolarizes toward " + M + "70 mV.",
             "Fewer voltage-gated calcium channels at the base are open, so glutamate release falls."]),
     ("ul", ["The cascade amplifies at each step, so a rod can respond to a single photon.",
             "Photoreceptors make graded potentials only. The first action potentials are in the ganglion cells, whose axons form the optic nerve."]),
   ]),
   ("Rods, cones and the visual pathway", [
     ("table", ["", "Rods", "Cones"],
      [["Light needed", "Dim (very sensitive)", "Bright"], ["Color", "No", "Yes"],
       ["Where", "Most of the retina outside the fovea", "Packed in the fovea"],
       ["Convergence onto ganglion cells", "High: sensitive, low acuity", "Low, often one to one: high acuity"]]),
     ("ol", ["Optic nerve from each eye.",
             "Optic chiasm: fibers from the inner (nasal) half of each retina cross; fibers from the outer half stay on their own side.",
             "Optic tract to the thalamus (lateral geniculate nucleus).",
             "Visual cortex in the occipital lobe."]),
     ("table", ["Lesion", "Field loss"],
      [["One optic nerve, before the chiasm", "All vision in that eye"],
       ["Middle of the chiasm (pituitary tumor)", "Outer (temporal) half of each eye's field: bitemporal hemianopia, often unnoticed for a long time"]]),
   ]),
  ]),

 dict(slug="hearing-balance", file="biol005-w05-hearing-balance-walkthrough-notes.html",
  title="Hearing, balance, taste and smell", walk="biol005-w05-hearing-balance-guided.html",
  comps="Week 5 competencies 20 to 23",
  sections=[
   ("Hearing", [
     ("ol", ["Sound, a pressure wave in air, vibrates the tympanic membrane.",
             "The ossicles (malleus, incus, stapes) carry the vibration to the oval window. The eardrum is about 20 times the area of the oval window, so the same force on a smaller area gives a higher pressure, enough to move fluid instead of reflecting off it.",
             "The oval window pushes on the cochlear fluid; the round window bulges out to let the fluid move.",
             "The pressure wave moves the basilar membrane.",
             "Stereocilia bend toward the tallest; tip links pull mechanically gated channels open.",
             "Potassium enters from the high-potassium endolymph and the hair cell depolarizes.",
             "Voltage-gated calcium channels open at the base and glutamate is released onto auditory nerve fibers, which fire faster."]),
     ("ul", ["Pitch is coded by place: high frequencies peak near the base (narrow, stiff), low frequencies near the apex (wide, flexible).",
             "Loudness is coded by rate: bigger movement, more transmitter, faster firing, more fibers recruited.",
             "Hair cells make graded receptor potentials, not action potentials."]),
   ]),
   ("Hearing loss and the tuning fork tests", [
     ("defs", [("Conductive loss", "Sound cannot get through the outer or middle ear (earwax, fluid, stiff ossicles)."),
               ("Sensorineural loss", "Damage to the cochlea or the auditory nerve."),
               ("Bone conduction", "Vibration carried through the skull straight to the cochlea, bypassing the outer and middle ear.")]),
     ("table", ["", "Weber (fork on the midline)", "Rinne (bone, then air, same ear)"],
      [["Normal", "Heard equally or in the middle", "Air longer than bone"],
       ["Conductive loss in one ear", "Louder in the affected ear", "Bone longer than air in the affected ear"],
       ["Sensorineural loss in one ear", "Louder in the good ear", "Air longer than bone, both shorter in the affected ear"]]),
     ("p", "Weber alone shows the ears differ but not which kind of loss; Rinne in the ear Weber points to tells you."),
   ]),
   ("Balance", [
     ("table", ["", "Semicircular canals", "Utricle and saccule"],
      [["Detects", "Rotation (angular acceleration)", "Head position relative to gravity and linear acceleration"],
       ["Structure", "Hair cells in a gel cupula spanning each canal", "Hair cells in a macula under a gel layer weighted with otoliths"],
       ["How hairs bend", "Endolymph lags behind the moving canal and pushes the cupula", "The heavy otolith layer slides or lags"]]),
     ("ul", ["During a steady spin the endolymph catches up, the cupula returns upright and the turning signal fades.",
             "On stopping, the endolymph keeps moving and bends the cupula the other way, so you feel turning in the opposite direction.",
             "The utricle mainly signals horizontal movement and tilt; the saccule vertical movement."]),
   ]),
   ("Taste and smell", [
     ("table", ["", "Taste", "Smell"],
      [["Receptor cell", "Taste cell, not a neuron; passes its signal to a sensory neuron", "Olfactory receptor neuron, itself a neuron"],
       ["Transduction", "Salty: Na+ enters through channels. Sour: H+ through ion channels. Sweet, bitter, umami: G protein-coupled receptors", "Odorant receptor (G protein-coupled) raises cAMP, which opens cation channels"],
       ["Route", "Medulla, thalamus, gustatory cortex", "Olfactory bulb, then olfactory cortex and limbic system, with no thalamic relay first"]]),
     ("p", "Because smell reaches the amygdala and hippocampus directly, a smell can call up emotion and memory before the smell is named."),
   ]),
  ]),
]
