"""
tools/walkthrough_notes_w04.py

The written notes that go with each Week 4 guided walkthrough. Sep 27 2026,
Scrubs: every walkthrough gets a set of real notes, not a repeat of the slides,
in bullet form, with definitions and sequences, and a printable PDF.

The content comes from the walkthroughs themselves, which were checked against
Silverthorn and the course notes when they were built. Nothing here adds a new
fact that is not already taught in the walkthrough or the Week 4 lecture notes.

Sep 27 2026 language pass: the notes now use the same scientific terms as the
revised walkthroughs (equilibrium potential, concentration, electrical and
electrochemical gradient, driving force, after-hyperpolarization), with no
metaphors standing in for mechanisms.

Block types:  ("p", text)  ("ul", [..])  ("ol", [..])  ("defs", [(term, def)])
              ("table", [header], [[row]...])  ("h3", text)
Run: python3 tools/make_walkthrough_notes.py
"""
M = "−"

DIV = "÷"
NOTES = [
 dict(slug="neurons-glia", file="biol005-w04-neurons-glia-walkthrough-notes.html",
  title="Neurons and neuroglia", walk="biol005-w04-neurons-glia-guided.html",
  comps="Week 4 competencies 7 to 11",
  sections=[
   ("Organization of the nervous system", [
     ("ul", ["The central nervous system (CNS) is the brain and spinal cord. It is the integrating center: it receives incoming information, combines it with everything else going on, and selects a response.",
             "The peripheral nervous system (PNS) is all the neural tissue outside the CNS: the cranial nerves, the spinal nerves, and their ganglia. It carries signals between the CNS and the rest of the body, in both directions.",
             "The sensory division, also called the afferent division, carries information toward the CNS from receptors in the skin, muscles, eyes, ears and internal organs. Most signals from the organs never reach awareness.",
             "The efferent division carries signals away from the CNS to effectors, which are muscles and glands."]),
     ("table", ["Efferent branch", "What it controls", "Example"],
      [["Somatic motor division", "Skeletal muscle", "Picking up a pencil (voluntary); many reflexes"],
       ["Autonomic division (visceral nervous system)", "Smooth muscle, cardiac muscle, glands, some adipose tissue", "Heart rate speeding up (involuntary)"]]),
     ("ul", ["The autonomic division has two branches that often have opposite effects on the same organ. The organ's activity at any moment reflects the balance between them.",
             "Sympathetic branch: fight-or-flight. Prepares the body for stress and effort, for example by raising heart rate and sending more blood to working muscles.",
             "Parasympathetic branch: rest-and-digest. Supports maintenance functions such as digestion, and slows the heart.",
             "Enteric nervous system: a network of neurons in the wall of the digestive tract that controls how the gut moves and what it secretes. It can detect a stimulus, integrate it and send out a response on its own, and the autonomic division normally adjusts it."]),
     ("defs", [("Afferent", "Carrying toward the CNS. The sensory division."),
               ("Efferent", "Carrying away from the CNS, toward effectors."),
               ("Effector", "A muscle or gland that carries out the response."),
               ("Integrating center", "The part of a pathway that receives incoming signals, sums them and selects a response. In the nervous system, the CNS.")]),
   ]),
   ("Functional classes and shapes of neurons", [
     ("table", ["By direction", "What it does", "Where"],
      [["Sensory (afferent) neuron", "Carries information toward the CNS", "Receptor to CNS"],
       ["Interneuron", "Connects other neurons; carries out integration. Roughly 99 percent of neurons are interneurons.", "Entirely inside the CNS"],
       ["Efferent (motor) neuron", "Carries signals away from the CNS to effectors", "CNS to effector"]]),
     ("ul", ["A typical neuron has dendrites, short branches that receive signals, and one axon, a long fiber that carries signals away from the cell body.",
             "Neurons are sorted by shape by counting the processes that leave the cell body."]),
     ("table", ["Shape", "Processes", "Where it is found"],
      [["Multipolar", "Many dendrites and one axon", "Most interneurons of the brain and spinal cord, and efferent neurons such as somatic motor neurons (cell bodies in the ventral horn)"],
       ["Bipolar", "One process on each side of the cell body", "Retina and olfactory epithelium, where they carry signals in the pathways for vision and smell"],
       ["Pseudounipolar", "One stalk that splits into a peripheral branch and a central branch", "Sensory neurons for touch, pain and stretch; cell bodies in the dorsal root ganglia"]]),
     ("ul", ["In a pseudounipolar neuron the action potential travels along one continuous axon, from the peripheral branch straight into the central branch, so the cell body is not in the conduction pathway. The cell body sits to one side in a dorsal root ganglion and still makes the proteins the neuron needs.",
             "Sensory fibers enter the spinal cord through the dorsal root and efferent fibers leave through the ventral root. If one dorsal root is cut, sensation in the area it serves is lost but voluntary movement is kept. Reflexes in that area are lost too, because the afferent half of each reflex pathway has been cut."]),
   ]),
   ("Functional regions of a neuron", [
     ("ol", ["Dendrites receive signals from other cells. One neuron may receive synaptic input from thousands of others. The signals here are graded potentials: small, local, variable in size, and they get smaller as they spread.",
             "The cell body (soma) holds the nucleus and makes nearly all of the proteins the neuron needs. Signals from every dendrite spread into it and add together, which is called summation.",
             "The trigger zone, the axon hillock and the initial segment of the axon, is where the summed graded potentials are integrated: if the sum reaches threshold, an action potential starts here. It has the highest density of voltage-gated sodium channels in the neuron, so it has the lowest threshold and reaches threshold before any other region. In many sensory neurons the trigger zone lies near the receptor endings instead.",
             "The axon carries action potentials. An action potential is all or none: voltage-gated channels regenerate it at full size as it travels, so it arrives at the terminals the same size as it started. A motor axon from the lower spinal cord to a muscle of the foot can be close to a meter long.",
             "The axon terminals release neurotransmitter. When an action potential depolarizes the terminal, voltage-gated calcium channels open, calcium moves into the terminal down its concentration gradient, and the rise in calcium causes vesicles to fuse with the membrane and release neurotransmitter by exocytosis."]),
     ("ul", ["A stronger stimulus does not make a bigger action potential. It makes each sensory neuron fire more often, and it activates more neurons.",
             "An input on the cell body next to the trigger zone has a bigger effect there than an identical input at the far tip of a dendrite, because it has less distance over which to get smaller.",
             "If the calcium channels at the terminal are blocked, the action potential arrives normally but no calcium enters, so no neurotransmitter is released and the signal stops at the terminal."]),
     ("defs", [("Graded potential", "A small, local change in membrane potential whose size varies with the strength of the input and which gets smaller with distance."),
               ("Action potential", "A large, all-or-none signal that travels the length of the axon without getting smaller."),
               ("Trigger zone", "The axon hillock and initial segment, where the summed graded potentials either reach threshold and start an action potential or do not."),
               ("Synapse", "The junction between an axon terminal and the next cell: a neuron, a muscle fiber or a gland cell. The gap between them is the synaptic cleft.")]),
   ]),
   ("Glial cells", [
     ("table", ["Glial cell", "Where", "Functions"],
      [["Astrocyte", "CNS", "Most common CNS glial cell. Regulates the extracellular fluid around neurons: takes up excess potassium after neurons fire, removes neurotransmitter such as glutamate from synapses, and helps deliver nutrients from the blood to neurons. Its end feet release signals that induce and maintain the tight junctions of the blood-brain barrier."],
       ["Oligodendrocyte", "CNS", "Forms myelin. One oligodendrocyte wraps segments of several axons."],
       ["Microglia", "CNS", "Resident immune cells. They survey the surrounding tissue, and when they detect damage, debris or pathogens they become activated and remove them by phagocytosis."],
       ["Ependymal cell", "CNS", "Lines the ventricles and central canal. Specialized ependymal cells produce cerebrospinal fluid; cilia help keep it circulating."],
       ["Schwann cell", "PNS", "Forms myelin. One Schwann cell wraps one segment of one axon. Helps cut peripheral axons regrow."],
       ["Satellite cell", "PNS", "Forms a capsule around neuron cell bodies in ganglia and regulates the fluid around them. Closely related to Schwann cells but does not form myelin."]]),
     ("ul", ["Blood-brain barrier: the endothelial cells of brain capillaries are joined by tight junctions. Small lipid-soluble molecules (oxygen, carbon dioxide, alcohol) cross easily; water-soluble molecules (glucose, amino acids) depend on transport proteins. The barrier keeps out many toxins, and also many drugs.",
             "If astrocytes cannot remove potassium, extracellular potassium rises, the resting membrane potential becomes less negative, and neurons rest closer to threshold. This is one way astrocyte dysfunction is thought to contribute to some seizure disorders.",
             "Hydrocephalus: if cerebrospinal fluid cannot drain, it accumulates, the ventricles upstream of the block enlarge, and the rising pressure compresses brain tissue. The fluid volume stays constant only when production equals drainage.",
             "Because one oligodendrocyte myelinates many axons, losing one oligodendrocyte removes myelin from many axons."]),
     ("h3", "When an axon is cut"),
     ("ol", ["The part of the axon separated from the cell body degenerates, because it no longer receives proteins from the cell body.",
             "In the PNS, Schwann cells survive, help clear debris, line up to form a tube and release growth factors, and the axon can regrow along that path, at roughly a millimeter a day.",
             "In the CNS, oligodendrocytes and astrocytes release molecules that inhibit regrowth, and astrocytes form a glial scar."]),
   ]),
   ("Myelin and what happens when it is lost", [
     ("ul", ["Myelin is the plasma membrane of a glial cell wound around the axon many times. Membrane is mostly lipid and ions cannot cross the lipid bilayer on their own, so myelin acts as electrical insulation.",
             "Myelin covers the axon in segments. The short uncovered gaps between them are the nodes of Ranvier.",
             "Voltage-gated sodium channels are densely clustered at the nodes, with very few in the membrane under the myelin.",
             "The slow step in conduction is the opening of voltage-gated channels that regenerates the action potential, not current flowing along the inside of the axon. Myelin reduces current leak, so current from one node reaches the next node still strong enough to bring it to threshold and regenerate the action potential there.",
             "The action potential is regenerated only at the nodes, so it effectively jumps from node to node. This is saltatory conduction. More nodes over the same distance would mean more regeneration steps and slower conduction.",
             "In electrical terms, myelin raises membrane resistance (less current leaks out) and lowers membrane capacitance (less charge is needed to change the voltage). A wider axon also conducts faster, because it has less resistance to current flowing along the inside."]),
     ("table", ["Axon", "Conduction speed"],
      [["Large, myelinated", "Up to about 120 m/s"],
       ["Thin, unmyelinated", "About 0.5 to 2 m/s"]]),
     ("h3", "Demyelination"),
     ("ol", ["The myelin over a stretch of axon is destroyed and the axon membrane underneath is exposed.",
             "Current leaks out across the bare stretch.",
             "Because that membrane was covered before, it has very few sodium channels to regenerate the action potential.",
             "If the stretch is long enough, the current fades before the next node reaches threshold, and the action potential stops. This is conduction block."]),
     ("table", ["Disease", "Myelin attacked", "Pattern"],
      [["Multiple sclerosis", "CNS myelin, formed by oligodendrocytes", "Symptoms that seem unrelated (vision, sensation, strength, balance) depending on which axons lose myelin. They come and go as areas become inflamed and then partly recover. A rise in body temperature can briefly bring barely conducting axons into conduction block."],
       ["Guillain-Barré syndrome", "PNS myelin, formed by Schwann cells", "In its most common form, an immune attack on peripheral myelin that often follows an infection. Weakness spreads up the legs and reflexes are lost; conduction is slowed but the response size is near normal, so the axons are largely intact. Most people recover over weeks to months because Schwann cells remyelinate axons effectively."]]),
   ]),
   ("Axonal transport", [
     ("ul", ["Nearly all proteins are made in the cell body. Almost nothing is made in the axon or terminals, so enzymes, membrane and vesicles have to be transported there from the cell body.",
             "Cargo travels along microtubules that run the length of the axon. Motor proteins carry it step by step and hydrolyze one ATP for each step. If the microtubules are disassembled, transport stops in both directions."]),
     ("table", ["Direction", "Motor protein", "Cargo"],
      [["Anterograde: cell body to terminals", "Kinesin", "Synaptic vesicles, new membrane proteins such as channels, mitochondria"],
       ["Retrograde: terminals to cell body", "Dynein", "Worn-out membrane and organelles for recycling, growth factors released by the target cell"]]),
     ("table", ["Speed", "Rate", "Carries"],
      [["Fast transport", "Up to about 400 mm per day", "Vesicles and mitochondria"],
       ["Slow transport", "About 0.2 to 2.5 mm per day", "Cytoskeleton proteins and dissolved enzymes"]]),
     ("ul", ["At 400 mm per day, fast transport covers a 1 meter axon in about 2.5 days.",
             "The slow rate of slow transport helps explain why a cut peripheral axon regrows only about a millimeter a day: the new axon is built largely from cytoskeleton proteins that arrive by slow transport.",
             "If outward transport is blocked at one point, outward cargo accumulates on the cell body side of the block. If inward transport is blocked, returning cargo accumulates on the terminal side. If dynein fails, worn-out material and growth factors no longer return to the cell body, and over time the neuron degenerates.",
             "Retrograde transport is also a route of infection. Rabies virus is taken up at motor neuron terminals in muscle and carried back along the axon. The cell bodies of these motor neurons are in the spinal cord, so the virus arrives directly in the CNS and then spreads from neuron to neuron to the brain. Tetanus toxin travels the same retrograde route.",
             "Herpes viruses use both directions: retrograde transport carries them to a sensory neuron cell body, where they remain dormant, and years later anterograde transport carries them back out along the same axon, which is why a cold sore returns in the same spot."]),
   ]),
  ]),

 dict(slug="rmp", file="biol005-w04-rmp-walkthrough-notes.html",
  title="The resting membrane potential", walk="biol005-w04-rmp-guided.html",
  comps="Week 4 competencies 1 to 5",
  sections=[
   ("How much of each ion", [
     ("table", ["Ion", "Inside (mM)", "Outside (mM)"],
      [["K+", "150", "5"], ["Na+", "15", "145"], ["Cl" + M, "10", "108"], ["Ca2+", "0.0001", "1"],
       ["Large anions (proteins, ATP)", "Many", "Almost none"]]),
     ("ul", ["Values vary slightly between textbooks, but the pattern is the same.",
             "Potassium is the only ion in the table that is more concentrated inside than outside. Sodium, chloride and calcium are all more concentrated outside.",
             "The large anions are too big to cross the membrane. They are the negative charge left behind when potassium leaves.",
             "Ions cannot cross the lipid bilayer on their own. They need channels, which are proteins built from the instructions in genes."]),
   ]),
   ("How the inside becomes negative", [
     ("ol", ["The membrane has many potassium leak channels, which are always open.",
             "Potassium is more concentrated inside, so it diffuses out through them, down its concentration gradient.",
             "Each potassium ion carries a positive charge out and leaves an unpaired negative charge behind, so the inside becomes negative. The separated charge collects in a very thin layer along the membrane, and only a tiny fraction of the cell's potassium has to leave to produce it.",
             "The negative inside attracts potassium back in, so the electrical gradient on potassium acts inward. It grows as more potassium leaves.",
             "When the electrical gradient is equal and opposite to the concentration gradient, potassium moves in and out at equal rates, with no net movement. That membrane potential is potassium's equilibrium potential, about " + M + "90 mV.",
             "A few open sodium channels let a small amount of sodium in, carrying positive charge in and making the inside slightly less negative. The resting potential is about " + M + "70 mV."]),
     ("ul", ["Permeability is how easily an ion crosses the membrane, and it depends mainly on how many of that ion's channels are open. The ion with the highest permeability has the most influence on the membrane potential. At rest a neuron is roughly 25 times more permeable to potassium than to sodium.",
             "If every potassium channel were blocked, potassium could no longer carry positive charge out, but sodium would keep leaking in, so the inside would become less negative. The potassium leak channels are the main reason the inside is negative at all."]),
     ("defs", [("Resting membrane potential", "The voltage across the membrane of a cell at rest, inside relative to outside, about " + M + "70 mV in a neuron."),
               ("Concentration gradient", "The difference in an ion's concentration across the membrane, also called the chemical gradient. It depends only on concentration, not on charge."),
               ("Electrical gradient", "The effect of the membrane potential on a charged ion. It depends only on the ion's charge and the membrane potential, not on concentration."),
               ("Electrochemical gradient", "The concentration gradient and the electrical gradient together. It determines the direction of an ion's net movement."),
               ("Equilibrium potential", "The membrane potential at which the electrical gradient on an ion is equal and opposite to its concentration gradient, so the ion has no net movement."),
               ("Permeability", "How easily an ion crosses the membrane, set mainly by how many of its channels are open.")]),
   ]),
   ("The electrochemical gradient", [
     ("table", ["Ion", "Concentration gradient", "Electrical gradient at " + M + "70 mV", "Result"],
      [["K+", "Outward", "Inward", "They oppose each other; a small net outward force"],
       ["Na+", "Inward", "Inward", "Both act inward; a large net inward force"]]),
     ("table", ["Ion", "Equilibrium potential (about)"],
      [["K+", M + "90 mV"], ["Na+", "+60 mV"], ["Cl" + M, M + "65 mV"], ["Ca2+", "+120 mV"]]),
     ("ul", ["The difference between the membrane potential and an ion's equilibrium potential is the driving force on that ion.",
             "At " + M + "70 mV, potassium is 20 mV from its equilibrium potential and sodium is 130 mV from its, so the driving force on sodium is much larger.",
             "The membrane potential is measured with a microelectrode inside the cell and a reference electrode outside, and it is always stated as the inside relative to the outside."]),
     ("defs", [("Driving force", "The difference between the membrane potential and an ion's equilibrium potential.")]),
   ]),
   ("Which way will it move?", [
     ("ul", ["When an ion's channels open, net movement of that ion drives the membrane potential toward that ion's equilibrium potential.",
             "When its channels are closed, the ion cannot cross, however large its electrochemical gradient.",
             "At " + M + "70 mV, if sodium channels open, sodium moves in, because its concentration gradient and the electrical gradient both act inward. The membrane depolarizes toward +60 mV.",
             "At +30 mV, if potassium channels open, potassium moves out with a large driving force: 120 mV from its equilibrium potential, compared with 20 mV at rest. Potassium carries positive charge out and the membrane potential falls. This is how the membrane repolarizes during an action potential."]),
   ]),
   ("The Nernst and Goldman equations", [
     ("ul", ["In this course you read and interpret these equations; you do not calculate with them.",
             "The Nernst equation calculates one ion's equilibrium potential from its concentrations outside and inside the cell. Potassium at 150 mM inside and 5 mM outside gives about " + M + "90 mV.",
             "If outside potassium rises from 5 to 10 mM, potassium's equilibrium potential becomes less negative, about " + M + "72 mV, because the concentration gradient driving potassium out is smaller. This is why high blood potassium depolarizes cells.",
             "The Goldman equation calculates the membrane potential from the concentrations of several ions and the membrane's permeability to each. It works much like a weighted average of the equilibrium potentials, with each ion weighted by its permeability.",
             "Potassium's permeability is by far the largest, so the resting potential lies near " + M + "90 mV, and sodium's small permeability shifts it to about " + M + "70 mV.",
             "Opening more potassium leak channels moves the membrane potential closer to " + M + "90 mV (hyperpolarization). Opening many sodium channels makes sodium permeability exceed potassium permeability, so the membrane potential rises toward +60 mV. This rapid depolarization is the rising phase of an action potential."]),
   ]),
   ("What the pump does and does not do", [
     ("ul", ["The sodium-potassium pump (Na+/K+ ATPase) uses energy from ATP to move ions against their concentration gradients: for each ATP it hydrolyzes, it moves 3 Na+ out and 2 K+ in.",
             "Its main job is to maintain the concentration gradients over minutes to hours, because sodium leaks in and potassium leaks out continuously.",
             "Because each cycle moves 3 positive charges out and only 2 in, the pump also makes the inside slightly more negative directly, but only by a few millivolts.",
             "It does not set the " + M + "70 mV resting potential from moment to moment; the leak channels do that. If the pump stops, the membrane potential changes by only a few millivolts at first. Over hours it drifts toward 0 mV as the concentration gradients run down."]),
   ]),
   ("Terms for voltage changes", [
     ("defs", [("Depolarization", "The membrane potential becomes less negative than rest (moves toward zero or above)."),
               ("Overshoot", "The part of an action potential where the inside is positive."),
               ("Repolarization", "The membrane potential returns toward its resting value, even while the inside is still positive."),
               ("Hyperpolarization", "The membrane potential becomes more negative than rest.")]),
     ("ul", ["These terms describe the direction of the change relative to the resting potential, not whether the inside is positive or negative.",
             "Channels come in four kinds: leak channels (no gate, always open), voltage-gated, ligand-gated (chemically gated) and mechanically gated. The channel gating walkthrough covers these in detail."]),
   ]),
   ("Resting potential and excitability", [
     ("ul", ["A neuron fires an action potential when its membrane is depolarized to threshold, about " + M + "55 mV. The difference between the resting potential and threshold is the depolarization needed to fire, and it determines how excitable the cell is.",
             "A cell that is depolarized is usually more excitable. If a cell stays depolarized for a long time, the inactivation gates of its voltage-gated sodium channels stay closed, fewer channels are available to open, and the cell becomes less excitable."]),
     ("table", ["Condition", "Blood K+ (normal 3.5 to 5.0 mM)", "K+ equilibrium potential", "Resting potential", "Effect"],
      [["Hyperkalemia (missed dialysis)", "7.0 mM", "About " + M + "81 mV", "About " + M + "65 mV, depolarized", "At first closer to threshold; if it lasts, sodium channels stay inactivated and cells can barely fire action potentials. In the heart: slow, disorganized conduction and risk of cardiac arrest."],
       ["Hypokalemia (loop diuretic)", "2.8 mM", "About " + M + "105 mV", "About " + M + "76 mV, hyperpolarized", "Farther from threshold, so a larger depolarization is needed to fire: muscle weakness and cramps. Low potassium also makes digoxin toxicity more likely."]]),
     ("ul", ["Treating hyperkalemia: IV calcium gluconate protects the heart by raising the threshold of cardiac cells, without changing the potassium level. Insulin with glucose lowers blood potassium by stimulating the sodium-potassium pump, which moves potassium into cells; the potassium is still in the body, so the effect lasts only a few hours. Dialysis is the only one of the three that removes potassium from the body.",
             "Lidocaine blocks voltage-gated sodium channels, not the leak channels, so the resting potential barely changes. A stimulus still depolarizes the membrane, but sodium cannot pass through the blocked channels, so no action potentials are generated and no pain is felt. A normal resting potential is necessary for a neuron to signal, but it is not sufficient on its own."]),
   ]),
  ]),

 dict(slug="channel-gating", file="biol005-w04-channel-gating-walkthrough-notes.html",
  title="Ion channel gating", walk="biol005-w04-channel-gating-guided.html",
  comps="",
  sections=[
   ("Leak channels and gated channels", [
     ("ul", ["An ion channel is a membrane protein with a water-filled pore that lets specific ions cross the membrane.",
             "A leak channel has no gate, so its pore is open all the time. Each leak channel is selective: it lets only certain ions through, and those ions move through it continuously, down their concentration and electrical gradients.",
             "In a resting neuron most leak channels are potassium leak channels. Potassium leaving through them is the main reason the resting membrane potential is negative.",
             "Most ion channels are gated. Part of the channel protein, the gate, blocks the pore when the channel is closed. When a specific stimulus acts on the channel, it causes a conformational change, a change in the shape of the protein, that moves the gate out of the pore so ions can pass.",
             "Leak channels set the resting membrane potential. Gated channels change the membrane potential at a specific time, in response to a specific stimulus, and that change is the signal."]),
     ("defs", [("Leak channel", "A selective channel with no gate, open all the time."),
               ("Gated channel", "A channel with a gate that opens only in response to a specific stimulus."),
               ("Conformational change", "A change in the shape of a protein. In a gated channel it moves the gate out of the pore.")]),
   ]),
   ("What opens a gate", [
     ("table", ["Channel", "Opens when", "Where you meet it"],
      [["Voltage-gated", "The membrane potential changes. A voltage sensor, a region of the protein with charged amino acids that sits in the electric field across the membrane, moves when the membrane depolarizes, and that causes a conformational change that opens the gate.", "The sodium and potassium channels of axons; calcium channels in axon terminals"],
       ["Ligand-gated (chemically gated)", "A specific ligand binds to a binding site on the channel. The binding site fits only molecules with a particular shape and charge, which is why each channel responds to specific ligands. Binding causes a conformational change that opens the gate, and the channel stays open while the ligand is bound.", "Acetylcholine receptors at the neuromuscular junction, where a motor neuron meets a skeletal muscle fiber"],
       ["Mechanically gated", "The membrane is stretched, bent or pressed. The deformation changes the shape of the channel protein and opens the gate. No voltage change or ligand is needed.", "Touch receptors in the skin, hair cells of the inner ear, stretch receptors in the walls of blood vessels"]]),
     ("ul", ["Positive feedback in voltage-gated sodium channels: channels open when the membrane depolarizes, sodium enters and depolarizes the membrane further, and that opens more channels. This is why an action potential, once it reaches threshold, always goes to its full size.",
             "Ligand-gated channels are the basis of chemical synaptic transmission. One cell releases a neurotransmitter, it diffuses across the synaptic cleft, and it binds to ligand-gated channels on the next cell.",
             "A drug that binds to the acetylcholine binding sites without opening the channels prevents acetylcholine from binding. The channels stay closed, the muscle fiber does not depolarize, no action potential starts in the muscle, and the muscle does not contract: weakness or paralysis. Some paralytic drugs used during surgery work this way.",
             "In myasthenia gravis, antibodies attack these acetylcholine receptors and reduce their number, which causes muscle weakness that worsens with repeated use.",
             "Mechanically gated channels carry out sensory transduction for touch, hearing and the sensing of blood pressure: the mechanical stimulus opens the channels, ions cross the membrane, and the membrane potential changes."]),
     ("defs", [("Sensory transduction", "The conversion of a stimulus, such as pressure, sound vibration or stretch, into an electrical signal.")]),
   ]),
   ("The sodium channel has two gates", [
     ("ul", ["Activation gate: closed at rest; opens quickly when the membrane depolarizes.",
             "Inactivation gate: on the cytoplasmic side of the channel. Open at rest; closes more slowly in response to the same depolarization, and then blocks the pore.",
             "Sodium can pass only when both gates are open."]),
     ("table", ["State", "Activation gate", "Inactivation gate", "Na+ passes?", "Can it open now?"],
      [["Resting (closed)", "Closed", "Open", "No", "Yes, if the membrane depolarizes"],
       ["Open", "Open", "Open", "Yes, sodium enters rapidly", "It is open"],
       ["Inactivated", "Open (or closed briefly during repolarization)", "Closed, blocking the pore", "No", "No, however strong the stimulus"]]),
     ("h3", "The sequence each time the channel opens"),
     ("ol", ["At the resting potential, about " + M + "70 mV, the channel is in the resting state.",
             "As the membrane depolarizes, activation gates begin to open. At threshold, about " + M + "55 mV, enough sodium channels are open that sodium entering the cell outpaces potassium leaving it, and the depolarization becomes self-reinforcing.",
             "Sodium enters rapidly, because its concentration gradient and the electrical gradient both act inward, and the membrane potential rises to about +30 mV. This is the rising phase of the action potential.",
             "About a millisecond after the activation gate opens, the inactivation gate closes and blocks the pore from the cytoplasmic side. Sodium entry stops automatically, because the same depolarization that opened the channel also closes it.",
             "The membrane repolarizes, mainly because potassium leaves the cell.",
             "Only then does the channel return to the resting state: the activation gate closes, then the inactivation gate reopens, and the channel can open again."]),
     ("defs", [("Inactivation", "The inactivation gate blocking the pore. A channel in the resting state can open when the membrane depolarizes; an inactivated channel cannot open, no matter how strong the stimulus."),
               ("Absolute refractory period", "The time after an action potential when most sodium channels are inactivated, so no stimulus, however strong, can produce another action potential in that region. It limits how many action potentials a neuron can produce per second, and it is why an action potential travels in one direction along an axon."),
               ("Return to the resting state", "Recovery from inactivation, which happens only after the membrane repolarizes.")]),
   ]),
   ("The voltage-gated potassium channel", [
     ("ul", ["It opens in response to the same depolarization as the sodium channel, but it has a single gate and it opens more slowly.",
             "It opens at about the time the sodium channels are inactivating, and potassium leaving the cell repolarizes the membrane.",
             "It is also slow to close, so potassium keeps leaving after the membrane potential has returned to its resting value. The membrane potential becomes more negative than rest until those channels close.",
             "After-hyperpolarization, also called the undershoot, is that period below the resting potential. It contributes to the relative refractory period, when a stronger than normal stimulus is needed to fire the neuron, because the membrane is farther from threshold than usual."]),
     ("defs", [("After-hyperpolarization", "The period after repolarization when the membrane potential is more negative than rest, because voltage-gated potassium channels are slow to close.")]),
   ]),
   ("Clinical applications", [
     ("table", ["Patient", "What happens", "Why"],
      [["Local anesthetic (lidocaine) before a dental procedure", "Within a few minutes the gums and lip on that side are numb", "Lidocaine binds inside the pore of voltage-gated sodium channels and blocks it, so sodium cannot enter even when the activation gate opens. The axon cannot produce action potentials, so the pain signal is not conducted to the brain. Lidocaine binds most readily to open and inactivated channels, so it blocks frequently firing nerves most effectively, and small pain fibers are blocked at lower concentrations than large motor fibers."],
       ["Severe hyperkalemia", "Excitable tissue stops responding; life-threatening arrhythmias in the heart", "High extracellular potassium keeps the membrane depolarized, so sodium channels stay inactivated and do not return to the resting state."],
       ["Hyperkalemic periodic paralysis", "Episodes of severe muscle weakness that start during rest after exercise or after eating potassium-rich foods; blood potassium is often high during an episode; strength is normal between episodes", "An inherited mutation in the skeletal muscle sodium channel impairs inactivation. Channels that do not inactivate completely keep letting sodium in and hold the membrane depolarized, which keeps most sodium channels, including the normal ones, inactivated. The muscle fiber cannot produce action potentials, so it cannot contract. Sustained depolarization stops activity rather than increasing it."]]),
   ]),
  ]),

 dict(slug="graded-potentials", file="biol005-w04-graded-potentials-walkthrough-notes.html",
  title="Graded potentials", walk="biol005-w04-graded-potentials-guided.html",
  comps="Week 4 competencies 12 and 14",
  sections=[
   ("Two kinds of electrical signal", [
     ("table", ["", "Graded potential", "Action potential"],
      [["Where", "Input zone: dendrites and cell body", "Starts at the trigger zone, travels the axon"],
       ["Size", "Varies with the strength of the stimulus", "Always the same size (all or none)"],
       ["Distance", "Short; gets smaller with distance", "Long; does not get smaller"],
       ["Threshold", "None", "Generated only if the trigger zone reaches threshold"],
       ["Channels", "Chemically (ligand) gated or mechanically gated", "Voltage-gated sodium and potassium"]]),
   ]),
   ("Graded potentials on a dendrite", [
     ("ol", ["A stimulus opens gated channels: a neurotransmitter binds to chemically gated channels at a synapse, or stretch opens mechanically gated channels in a sensory ending.",
             "Ions cross, and the membrane potential moves toward the equilibrium potential of the ion whose permeability increased.",
             "Sodium entering makes the inside less negative: a depolarizing graded potential. At a synapse this is an excitatory postsynaptic potential (EPSP), because it brings the neuron closer to firing an action potential.",
             "Potassium leaving makes the inside more negative than rest: a hyperpolarizing graded potential. At a synapse this is an inhibitory postsynaptic potential (IPSP), because it moves the membrane potential farther from threshold and makes the neuron less likely to fire.",
             "The channels close and the membrane returns to rest. A graded potential lasts from a few milliseconds to tens of milliseconds."]),
     ("ul", ["A stronger stimulus opens more channels or holds them open longer, so more ions cross and the change in voltage is larger. That is what graded means: the amplitude varies with the strength of the stimulus.",
             "Example amplitudes recorded at one site: weak stimulus 3 mV, medium 7 mV, strong 12 mV; a stimulus that opens potassium channels, about 8 mV below rest.",
             "In a sensory receptor, a graded potential produced by a stimulus such as stretch is called a receptor potential."]),
     ("defs", [("Graded potential", "A small change in membrane potential confined to one region of the membrane, whose amplitude varies with the strength of the stimulus."),
               ("EPSP (excitatory postsynaptic potential)", "A depolarizing graded potential produced by a neurotransmitter at a synapse."),
               ("IPSP (inhibitory postsynaptic potential)", "A hyperpolarizing graded potential produced by a neurotransmitter at a synapse."),
               ("Receptor potential", "A graded potential produced in a sensory receptor by a stimulus such as stretch.")]),
   ]),
   ("Why graded potentials fade", [
     ("ul", ["Local current flow: the positive charge that enters spreads along the inside of the dendrite in both directions, away from where it entered.",
             "Current leak: some of that charge leaves across the membrane through the open leak channels along the dendrite, the same leak channels that set the resting potential.",
             "Cytoplasmic resistance: the cytoplasm, which contains many proteins and other molecules, resists the flow of charge through it.",
             "Because of current leak and cytoplasmic resistance, the graded potential is smaller at every point farther from where it started. This loss of amplitude with distance is decremental conduction. Example: 20 mV at point 1 next to the open channels, then 12, 7 and 4 mV at points farther along.",
             "A wider dendrite has a larger cross section for charge to flow through, so its cytoplasmic resistance is much lower. Current leak does not decrease; a wider dendrite has a little more membrane, and so more leak channels, along each length. Cytoplasmic resistance falls much more than leak rises, so the graded potential spreads farther."]),
     ("defs", [("Local current flow", "Movement of charge through the cytoplasm away from where ions entered."),
               ("Current leak", "Loss of charge across the membrane through open leak channels."),
               ("Cytoplasmic resistance", "The cytoplasm's resistance to the flow of charge; lower in a wider process."),
               ("Decremental conduction", "The decrease in a graded potential's amplitude with distance from where it started.")]),
   ]),
   ("What reaches the trigger zone", [
     ("ul", ["The trigger zone is the axon hillock and initial segment. An action potential is generated there only if the membrane potential at the trigger zone reaches threshold, about " + M + "55 mV. From rest at " + M + "70 mV that takes about 15 mV of depolarization.",
             "The outcome depends on the amplitude of the graded potential when it arrives at the trigger zone, not its amplitude where it started.",
             "Graded potentials that overlap in time add together: summation. EPSPs move the membrane potential toward threshold and IPSPs move it away. An action potential is generated only if the net depolarization reaches threshold.",
             "Spatial summation: graded potentials from different synapses that are active at the same time add together.",
             "Temporal summation: one synapse is activated again before its previous graded potential has faded, and the two add together.",
             "Real graded potentials that overlap add up to a little less than their simple sum, but the reasoning is the same."]),
     ("table", ["Inputs reaching the trigger zone", "Arithmetic", "Voltage", "Result"],
      [["One EPSP, 8 mV (20 mV at the synapse)", M + "70 + 8", M + "62 mV", "Subthreshold, no action potential"],
       ["Two EPSPs at the same time, 8 mV each", M + "70 + 8 + 8", M + "54 mV", "Suprathreshold, an action potential is generated"],
       ["Two EPSPs of 8 mV plus one IPSP of 5 mV", M + "70 + 8 + 8 " + M + " 5", M + "59 mV", "Subthreshold, no action potential"]]),
     ("defs", [("Threshold", "The membrane potential at the trigger zone, about " + M + "55 mV, at which an action potential is generated."),
               ("Subthreshold", "Too small to bring the trigger zone to threshold."),
               ("Suprathreshold", "Large enough to bring the trigger zone to threshold."),
               ("Summation", "The adding together of graded potentials that overlap in time."),
               ("Spatial summation", "Summation of graded potentials from different synapses active at the same time."),
               ("Temporal summation", "Summation of graded potentials from one synapse activated again before its previous graded potential has faded.")]),
   ]),
   ("Patient: the pufferfish meal", [
     ("ul", ["Tetrodotoxin blocks voltage-gated sodium channels from the outside of the cell. It does not block chemically gated or mechanically gated channels.",
             "His resting potential is normal (" + M + "70 mV). A weak stimulus still produces a small graded potential, about 5 mV, that fades.",
             "A strong stimulus produces about 20 mV, which goes past threshold, but no action potential appears, because the action potential depends on the voltage-gated sodium channels that the toxin blocks.",
             "His neurons can still produce graded potentials in response to input, but they cannot generate action potentials to carry signals along their axons. The action potential walkthrough finishes this case."]),
   ]),
  ]),
 dict(slug="action-potential", file="biol005-w04-action-potential-walkthrough-notes.html",
  title="The action potential", walk="biol005-w04-action-potential-guided.html",
  comps="Week 4 competencies 13 to 16",
  sections=[
   ("The key numbers", [
     ("table", ["Point", "Voltage", "What sets it"],
      [["Rest", M + "70 mV", "Mostly the potassium leak (resting potential walkthrough)"],
       ["Threshold", "about " + M + "55 mV", "The inward sodium current first exceeds the outward potassium current"],
       ["Peak", "about +30 mV", "Sodium inactivation gates close and voltage-gated potassium channels open"],
       ["After-hyperpolarization", "about " + M + "80 mV", "Voltage-gated potassium channels are slow to close"],
       ["Sodium equilibrium potential", "+60 mV", "The value the rising phase moves toward"],
       ["Potassium equilibrium potential", M + "90 mV", "The value the after-hyperpolarization moves toward"]]),
     ("p", "The whole action potential, from threshold back to rest, lasts a few milliseconds."),
   ]),
   ("The two voltage-gated channels", [
     ("table", ["Channel", "Gates", "At rest", "When depolarized"],
      [["Voltage-gated Na+ channel", "Activation gate, and inactivation gate on the cytoplasmic side", "Activation gate closed, inactivation gate open", "Activation gate opens quickly; inactivation gate closes a little later and stays closed until the membrane repolarizes"],
       ["Voltage-gated K+ channel", "One gate", "Closed", "Opens slowly, at about the time the sodium channels inactivate, and closes slowly"]]),
     ("ul", ["Both channels are opened by depolarization. The difference that shapes the action potential is timing: the sodium channel responds quickly and the potassium channel slowly.",
             "A stimulus can open activation gates, but no stimulus of any size can open an inactivation gate. It reopens only after the membrane repolarizes."]),
   ]),
   ("Reaching threshold", [
     ("ul", ["A graded potential depolarizes the trigger zone, the axon hillock and first part of the axon, and opens some voltage-gated sodium channels.",
             "Below threshold (example: a 10 mV graded potential brings the membrane to " + M + "60 mV), the inward sodium current is smaller than the outward potassium current through the leak channels. More positive charge leaves than enters, so the membrane returns to " + M + "70 mV and no action potential occurs.",
             "At threshold (a 15 mV graded potential brings the membrane to about " + M + "55 mV), the inward sodium current equals, then exceeds, the outward potassium current.",
             "Threshold is defined by this balance between two currents, so its exact value can vary from neuron to neuron."]),
     ("ol", ["Sodium enters and the membrane depolarizes.",
             "Depolarization opens more voltage-gated sodium channels.",
             "More sodium enters, and the membrane depolarizes further.",
             "Back to step 2. This cycle is positive feedback. Once it starts, the action potential no longer depends on the stimulus."]),
   ]),
   ("The phases", [
     ("table", ["Phase", "Voltage", "Na+ channels", "K+ channels", "Ion movement"],
      [["Rest", M + "70 mV", "Resting (activation gate closed)", "Closed", "Leak channels only"],
       ["Rising phase (depolarization)", M + "55 to about +30 mV", "Open", "Starting to open", "Na+ enters rapidly"],
       ["Peak (overshoot above 0 mV)", "about +30 mV", "Inactivation gates close", "Open", "Na+ entry stops; K+ starts to leave"],
       ["Falling phase (repolarization)", "+30 back to " + M + "70 mV", "Inactivated", "Open", "K+ leaves"],
       ["After-hyperpolarization", "down to about " + M + "80 mV, then back to rest", "Returning to the resting state: activation gate closes, inactivation gate opens", "Still open, closing slowly", "Extra K+ leaves, moving the membrane potential toward " + M + "90 mV"]]),
     ("ul", ["The rising phase moves toward the sodium equilibrium potential (+60 mV) because the membrane is now far more permeable to sodium than to anything else. This is the same rule as for the resting potential: the membrane potential moves toward the equilibrium potential of the ion the membrane is most permeable to.",
             "The voltage peaks near +30 mV, well short of +60 mV, because the sodium inactivation gates close and the voltage-gated potassium channels open.",
             "Potassium leaving through voltage-gated channels repolarizes the membrane. The sodium-potassium pump does not.",
             "The after-hyperpolarization happens because the voltage-gated potassium channels are slow to close, so for a few milliseconds the membrane is even more permeable to potassium than at rest and the membrane potential moves closer to the potassium equilibrium potential."]),
     ("defs", [("Threshold", "The membrane potential at which the inward sodium current first exceeds the outward potassium current and the action potential begins; about " + M + "55 mV here."),
               ("Positive feedback", "A cycle in which the result of a process strengthens the process itself: depolarization opens sodium channels, and the sodium that enters causes more depolarization."),
               ("Rising phase (depolarization)", "The rapid rise from threshold to the peak, carried by sodium entering the cell."),
               ("Overshoot", "The part of the action potential above 0 mV, when the inside is positive."),
               ("Falling phase (repolarization)", "The return from the peak toward rest, carried by potassium leaving the cell."),
               ("After-hyperpolarization", "The period after repolarization when the membrane potential is below the resting potential, caused by voltage-gated potassium channels that are slow to close.")]),
   ]),
   ("How many ions move", [
     ("ul", ["Only a tiny fraction of the ions cross the membrane during one action potential. Afterward, sodium inside is still about 15 mM and potassium inside is still about 150 mM.",
             "The concentration gradients remain after an action potential, so a neuron can fire again right away without waiting for the pump.",
             "The pump keeps the concentrations steady over the long term, across thousands of action potentials. It does not repolarize the membrane after each action potential."]),
   ]),
   ("All or none", [
     ("ul", ["Below threshold there is no action potential. At or above threshold there is a full-sized action potential every time.",
             "Example: graded potentials of 5 and 10 mV stay below threshold. Graded potentials of 16 and 30 mV both produce action potentials that peak at about +30 mV.",
             "Once threshold is reached, the size of the action potential is set by the voltage-gated channels and the sodium equilibrium potential, not by the stimulus. A larger graded potential only brings the membrane to threshold a little sooner."]),
     ("defs", [("All or none", "An action potential either occurs at full size or does not occur; its size does not depend on the size of the stimulus.")]),
   ]),
   ("Coding stimulus strength", [
     ("ul", ["Because every action potential is the same size, the size of an action potential cannot encode stimulus strength.",
             "Frequency coding: a stronger stimulus makes a single neuron fire more often. A larger graded potential at the trigger zone brings the membrane back to threshold sooner after each action potential. Example in the walkthrough: 2, 5 and 9 action potentials in the same period for weak, medium and strong stimuli.",
             "Population coding: a stronger stimulus activates more receptors, so more neurons fire. Example: the strong stimulus has four neurons firing instead of one.",
             "A single axon can use only frequency coding."]),
     ("defs", [("Frequency coding", "Encoding stimulus strength by how often a neuron fires."),
               ("Population coding", "Encoding stimulus strength by how many neurons fire.")]),
   ]),
   ("Refractory periods", [
     ("table", ["Period", "When", "Channel state", "Can a second action potential start?"],
      [["Absolute refractory period", "From the start of the action potential until the sodium channels begin to return to the resting state", "Na+ inactivation gates closed", "No, no matter how strong the stimulus"],
       ["Relative refractory period", "During the after-hyperpolarization", "Some Na+ channels have returned to the resting state; extra K+ channels still open", "Yes, but only with a stronger stimulus than usual, and the second action potential is often a little smaller"]]),
     ("ul", ["Example: during the after-hyperpolarization the membrane is near " + M + "78 mV. The same 16 mV stimulus that fired the first action potential brings it only to about " + M + "62 mV, below threshold.",
             "The absolute refractory period lasts about 1 to 2 ms, which sets an upper limit on firing rate: 1,000 ms " + DIV + " 2 ms = 500 per second, or 1,000 ms " + DIV + " 1 ms = 1,000 per second. Most neurons fire well below this.",
             "The refractory period also keeps the action potential traveling in one direction along the axon (conduction walkthrough)."]),
     ("defs", [("Absolute refractory period", "The time during which no stimulus of any size can start a second action potential, because the sodium inactivation gates are closed."),
               ("Relative refractory period", "The time that follows, during the after-hyperpolarization, when a second action potential can start but only with a stronger stimulus than usual.")]),
   ]),
   ("Patient: a drug that blocks potassium channels", [
     ("ul", ["Dalfampridine (4-aminopyridine) blocks voltage-gated potassium channels. It is used to help people with multiple sclerosis walk.",
             "In multiple sclerosis, axons lose myelin, which exposes potassium channels that are normally covered by it.",
             "With the voltage-gated potassium channels blocked, the rising phase and peak barely change, because they depend on sodium. The falling phase is much slower; the membrane still repolarizes as the sodium channels inactivate and potassium leaves through the leak channels. The action potential becomes wider, and the after-hyperpolarization mostly disappears.",
             "A wider action potential delivers more charge to the next segment of axon, which helps the signal cross a segment that has lost its myelin.",
             "Blocking these channels throughout the brain can also make neurons more excitable, so the dose is kept low: too much can cause seizures."]),
   ]),
  ]),
]
