"""
tools/walkthrough_notes_w05.py

The written notes that go with each Week 5 guided walkthrough. Oct 4 2026.
Same rules as tools/walkthrough_notes_w04.py: real notes in bullets,
definitions, sequences and tables, not a copy of the steps, and nothing here
that is not taught in the walkthrough itself.

Block types:  ("p", text)  ("ul", [..])  ("ol", [..])  ("defs", [(term, def)])
              ("table", [header], [[row]...])  ("h3", text)
Run: python3 tools/make_walkthrough_notes_w05.py
"""
M = "\u2212"

NOTES = [
 dict(slug="reflexes", file="biol005-w05-reflexes-walkthrough-notes.html",
  title="Spinal reflexes", walk="biol005-w05-reflexes-guided.html",
  comps="Week 5 competencies 1 to 4 and 7",
  sections=[
   ("Step by step: where the signal travels", [('h3', 'The knee jerk, step by step'), ('ol', ['A tap on the patellar tendon suddenly stretches the quadriceps.', 'The muscle spindles in the quadriceps are stretched with it. Mechanically gated channels in their sensory endings open and the endings depolarize: a receptor potential.', 'The spindle sensory neuron fires faster. Its action potentials travel up the femoral nerve toward the spinal cord.', 'The signal enters the cord through the dorsal root at levels L2 to L4. The cell body of this sensory neuron sits in the dorsal root ganglion, outside the cord.', 'Inside the gray matter, the axon branches. One branch synapses directly on an alpha motor neuron to the quadriceps in the ventral horn. This is the only synapse in the arc.', 'The alpha motor neuron fires. Its axon leaves through the ventral root and runs back down the femoral nerve to the quadriceps.', 'At the neuromuscular junction it releases acetylcholine, and the quadriceps contracts. The leg kicks.', 'At the same moment, a second branch excites an inhibitory interneuron. The interneuron releases glycine onto the hamstring motor neuron, which hyperpolarizes, so the hamstrings relax. This is reciprocal inhibition.', 'Other branches carry the information up the cord to the brain, so you become aware of the tap after the kick has already started.']), ('h3', 'Keeping the spindle working: alpha-gamma coactivation'), ('ol', ['The brain sends a command to contract the quadriceps.', 'Upper motor neurons excite alpha motor neurons, which shorten the working muscle fibers.', 'At the same time they excite gamma motor neurons, whose axons also leave through the ventral root.', 'Gamma motor neurons contract the two ends of the intrafusal fibers inside each spindle.', 'The middle of the spindle stays stretched, so the spindle keeps firing and keeps reporting muscle length as the muscle shortens.']), ('h3', 'The Golgi tendon reflex, step by step'), ('ol', ['The quadriceps contracts hard and pulls on its tendon.', 'The collagen fibers of the Golgi tendon organ tighten and squeeze its sensory ending.', "The tendon organ's sensory neuron fires faster as tension rises.", 'The signal enters the cord through the dorsal root. Its cell body is in the dorsal root ganglion.', 'It excites an inhibitory interneuron in the gray matter.', 'The interneuron inhibits the alpha motor neurons of the same muscle.', 'The quadriceps produces less force. This is the classic protective view; the textbook notes the tendon organ mainly informs the CNS about tension.']), ('h3', 'Withdrawal and crossed extensor, step by step'), ('ol', ['A tack pierces the skin of the right foot. Nociceptors depolarize and fire.', 'The signal travels up the sensory neurons in the sciatic nerve and enters the cord through the dorsal roots. Their cell bodies are in the dorsal root ganglia.', 'In the dorsal horn they synapse on interneurons. The interneurons spread the signal up and down several segments of the cord.', 'Right side: excitatory interneurons fire the motor neurons to the right flexors, which contract and lift the foot.', 'Right side: inhibitory interneurons quiet the motor neurons to the right extensors, which relax.', 'Other interneurons cross the midline of the cord to the left side.', "Left side: excitatory interneurons fire the motor neurons to the left extensors, which contract and take the body's weight. Inhibitory interneurons quiet the left flexors.", 'The pain signal also travels up the spinothalamic tract to the brain, so you feel the pain after the foot is already lifting.'])]),
   ("The reflex arc", [
     ("p", "A reflex is an automatic, stereotyped response to a stimulus. Spinal reflexes are integrated in the spinal cord and do not need the brain."),
     ("ol", ["Receptor: detects the stimulus (for the knee jerk, the muscle spindle).",
             "Sensory (afferent) neuron: carries the signal into the cord through the dorsal root. Its cell body is in the dorsal root ganglion.",
             "Integrating center: the spinal cord gray matter, where the sensory neuron synapses.",
             "Motor (efferent) neuron: carries the response out of the cord through the ventral root.",
             "Effector: the muscle or gland that responds (for the knee jerk, the quadriceps)."]),
     ("defs", [("Monosynaptic reflex", "The sensory neuron synapses directly on the motor neuron: one synapse. Fastest possible reflex. The stretch reflex is the example."),
               ("Polysynaptic reflex", "One or more interneurons between the sensory and motor neuron. Slower, because each synapse adds a delay of roughly half a millisecond, but able to inhibit, to cross the midline, and to reach several segments.")]),
     ("table", ["Cut", "Reflex", "Sensation from that area", "Voluntary movement"],
      [["Dorsal root", "Lost", "Lost", "Intact"],
       ["Ventral root", "Lost", "Intact", "Lost"]]),
   ]),
   ("Kinds of reflexes", [
     ("p", "Every neural reflex: stimulus, sensory receptor, sensory afferent neuron, CNS integrating center, efferent neuron, target muscle or gland. Many use negative feedback; some have a feedforward component that starts the response in anticipation, like bracing for a collision."),
     ("table", ["Sorted by", "Kinds", "Example"],
      [["Efferent division", "Somatic (somatic motor neurons, skeletal muscle) or autonomic (autonomic neurons; smooth and cardiac muscle, glands, adipose tissue)", "Knee jerk; pupillary light reflex"],
       ["Where integrated", "Spinal (spinal cord; the brain can modulate but is not required) or cranial (brain)", "Knee jerk; pupillary light reflex"],
       ["When it develops", "Innate (genetically determined) or learned, also called conditioned (acquired through experience)", "Rooting reflex in a newborn; Pavlov's dogs salivating at a bell"],
       ["Number of neurons", "Monosynaptic (two neurons, one synapse; only somatic motor reflexes) or polysynaptic (one or more interneurons; all autonomic reflexes)", "Knee jerk; withdrawal reflex"]]),
     ("ul", ["Polysynaptic pathways allow divergence (one stimulus, many targets), convergence (many inputs modify one response), and both excitation and inhibition.",
             "The pupillary light reflex is autonomic, cranial, innate and polysynaptic.",
             "Autonomic (visceral) reflexes: urination and defecation are spinal reflexes modulated by the brain (toilet training is learned control); the hypothalamus, thalamus and brain stem integrate heart rate, blood pressure, breathing, eating, water balance and body temperature; the brain stem integrates salivating, vomiting, sneezing, coughing, swallowing and gagging."]),
     ("h3", "An autonomic reflex, step by step"),
     ("ol", ["A stimulus activates a sensory receptor.",
             "The sensory neuron carries the signal into the CNS.",
             "It synapses on an interneuron in the integrating center.",
             "The interneuron synapses on a preganglionic autonomic neuron.",
             "The preganglionic neuron synapses on a postganglionic neuron in an autonomic ganglion, outside the CNS.",
             "The postganglionic neuron acts on the target: smooth muscle, cardiac muscle, a gland or adipose tissue."]),
   ]),
   ("Skeletal muscle reflexes and proprioceptors", [
     ("ol", ["Proprioceptors in muscles, joint capsules and ligaments sense length, tension and position. Their sensory neurons have cell bodies in the dorsal root ganglia.",
             "The CNS integrates the input through excitatory and inhibitory interneurons, mostly subconsciously; some reaches the cortex, and some reflexes can be modulated consciously.",
             "Alpha motor neurons carry the output.",
             "Extrafusal muscle fibers, the ordinary contractile fibers, are the effectors."]),
     ("ul", ["No neuron inhibits a skeletal muscle directly. Excitation always means contraction; relaxation is the absence of excitation, arranged by inhibition inside the CNS.",
             "The muscle spindle and Golgi tendon organ are the main proprioceptors; both are nerve endings in connective tissue capsules with mechanically gated cation channels. Joint receptors contribute less than once thought.",
             "Loss of proprioception, with disease or aging, can cause instability and falls."]),
   ]),
   ("The stretch reflex", [
     ("ul", ["Muscle spindles lie parallel to the extrafusal fibers; every skeletal muscle has many except one muscle in the jaw. Each spindle holds intrafusal fibers whose ends contract but whose central region lacks myofibrils and is wrapped by sensory endings.",
             "Spindles are tonically active, slowly adapting stretch receptors: at resting length the center is already stretched enough to fire them.",
             "Tonic spindle input keeps alpha motor neurons firing, so even a resting muscle has muscle tone, its resistance to stretch.",
             "Stretch reflex: a protective reflex against overstretching. Stretch speeds spindle firing; the afferent synapses directly on alpha motor neurons of the same muscle; the muscle contracts and the stretch is undone (negative feedback). Example: a book added to an outstretched hand.",
             "Reciprocal inhibition: spindle afferent branches excite inhibitory interneurons that silence the antagonist's motor neurons. The pathways controlling one joint form a myotatic unit.",
             "Alpha-gamma coactivation: gamma motor neurons contract the ends of the intrafusal fibers as the alpha motor neurons contract the muscle, keeping the spindle center stretched so it keeps firing."]),
     ("defs", [("Alpha motor neuron", "Motor neuron to the extrafusal fibers."),
               ("Gamma motor neuron", "Motor neuron to the contractile ends of the intrafusal fibers.")]),
   ]),
   ("The Golgi tendon organ", [
     ("ul", ["Free nerve endings wound between collagen fibers in a capsule at the muscle-tendon junction, in series with the muscle fibers.",
             "Responds mainly to tension, especially while the muscle pulls without shortening; relatively insensitive to stretch.",
             "Classic Golgi tendon reflex (autogenic inhibition): tendon organ afferent excites an inhibitory interneuron that inhibits the same muscle's motor neurons.",
             "Your textbook's update: the tendon organ's main role is sending tension information to CNS integrating centers, combined with spindle input for fine control of posture and movement."]),
     ("table", ["", "Muscle spindle", "Golgi tendon organ"],
      [["Position", "In parallel with the extrafusal fibers", "In series, at the muscle-tendon junction"],
       ["Reports", "Length (stretch)", "Tension (force)"],
       ["Classic reflex effect on its own muscle", "Excites: contract", "Inhibits: relax (autogenic inhibition)"],
       ["Synapses", "Monosynaptic to its own muscle", "Polysynaptic, through an inhibitory interneuron"],
       ["Held still while the load rises", "Steady firing", "Firing rises"]]),
     ("p", "Picking up a heavy weight: alpha motor neurons, gamma motor neurons, spindle afferents and tendon organ afferents are all active."),
   ]),
   ("Withdrawal and crossed extensor reflexes", [
     ("ol", ["Nociceptors in the right foot fire (stepping on a tack).",
             "The primary sensory neuron enters the cord and diverges onto many interneurons.",
             "Same side: excitatory interneurons drive the alpha motor neurons to the flexors, and inhibitory interneurons silence those to the extensors. The foot lifts: the flexion (withdrawal) reflex.",
             "Other side: interneurons cross the midline; the left extensors contract and the left flexors are inhibited, so the left leg takes the weight: the crossed extensor reflex, a postural reflex.",
             "One collateral ascends to the brain for the sensation of pain and for postural adjustment."]),
     ("ul", ["Both are polysynaptic, so the withdrawal reflex is slower than the monosynaptic stretch reflex.",
             "Divergence lets one stimulus control two antagonist pairs on both sides and inform the brain."]),
     ("h3", "Tetanus (lockjaw)"),
     ("ol", ["Clostridium tetani enters through a wound and releases the toxin tetanospasmin.",
             "The toxin is taken up into somatic motor neuron terminals by endocytosis.",
             "It travels backward along the axon to the cell body in the spinal cord.",
             "It is released and blocks neurotransmitter release at inhibitory synapses (inhibitory transmitters such as glycine and GABA hyperpolarize their targets).",
             "With no inhibition, agonists and antagonists contract together: rigid spasms beginning in the jaw and spreading, sometimes to the breathing muscles.",
             "Treatment can include antitoxin, antibiotics, muscle relaxants, and a drug that blocks acetylcholine receptors with ventilator support. Immunization prevents it."]),
   ]),
   ("The brain's control of spinal reflexes", [
     ("ul", ["Muscle tone: spindles fire at rest, keeping a few alpha motor neurons active, so a resting muscle is slightly firm. Cutting the dorsal roots removes tone and the tendon reflex.",
             "Descending pathways from the brain act on spinal motor neurons, interneurons and gamma motor neurons, and on balance they hold spinal reflexes in check.",
             "Jendrassik maneuver: pulling the hooked hands apart during the tap is thought to raise descending drive and spindle sensitivity, so a weak reflex gets bigger. A reflex that reinforces has an intact arc.",
             "Plantar response: stroking the sole normally curls the toes down. A big toe that extends with the toes fanning is the Babinski sign, an upper motor neuron sign. It is normal in infants until about one to two years old, while the corticospinal tract matures."]),
     ("table", ["", "Upper motor neuron lesion", "Lower motor neuron lesion"],
      [["Where", "Motor pathway in the brain or cord above the reflex (corticospinal tract)", "Ventral horn motor neuron, ventral root or peripheral nerve"],
       ["Strength", "Weak", "Weak"],
       ["Tone", "High (spasticity)", "Low (flaccid)"],
       ["Reflexes", "Brisk, often with clonus", "Reduced or absent"],
       ["Plantar response", "Babinski sign", "Normal or absent"],
       ["Over weeks", "Little wasting", "Muscle wasting and fasciculations"]]),
   ]),
   ("Testing reflexes", [
     ("table", ["Grade", "Meaning"],
      [["0", "Absent"], ["1+", "Less than usual"], ["2+", "Normal"], ["3+", "Brisker than usual"], ["4+", "Very brisk, often with clonus"]]),
     ("ul", ["A normal reflex needs normal conduction in every neuron, normal transmission at the neuromuscular junction, and normal muscle contraction.",
             "An absent reflex means the arc is broken somewhere: receptor, sensory neuron or dorsal root, cord segment, motor neuron or ventral root, neuromuscular junction, or muscle.",
             "Not all abnormal reflexes are neuromuscular: slowed relaxation of the ankle reflex suggests hypothyroidism.",
             "A very brisk reflex with clonus usually means the descending pathways from the brain that normally hold reflexes in check are damaged (an upper motor neuron lesion).",
             "Compare left with right. A difference between sides matters more than one number.",
             "Latency separates a reflex from a voluntary response. The knee jerk appears a few tens of milliseconds after the tap. Catching a dropped ruler takes about 150 to 250 milliseconds, because the path runs through the eyes, the brain and down the cord, crossing many more synapses."]),
   ]),
  ]),

 dict(slug="sensory-coding", file="biol005-w05-sensory-coding-walkthrough-notes.html",
  title="Sensory receptors and coding", walk="biol005-w05-sensory-coding-guided.html",
  comps="Week 5 competencies 8 to 12",
  sections=[
   ("Step by step: where the signal travels", [('h3', 'From touch to the brain, step by step'), ('ol', ['Pressure deforms the skin over a touch receptor.', 'Mechanically gated cation channels in the receptor ending open, Na+ enters, and the ending depolarizes. This graded change is the receptor potential.', 'The receptor potential spreads to the trigger zone. If it is above threshold there, voltage-gated Na+ channels open and the trigger zone fires action potentials.', 'A stronger stimulus gives a bigger receptor potential and a higher firing frequency, and it reaches the thresholds of more receptors.', 'The action potentials travel along the sensory axon, unchanged in size, through the peripheral nerve and the dorsal root to the spinal cord.', 'The signal climbs to the brain on its own pathway, a labeled line, and relays in the thalamus.', 'It reaches its own spot in the somatosensory cortex. Which line is active tells the brain the modality, and which spot is active tells it the location.']), ('h3', 'Lateral inhibition, step by step'), ('ol', ['A stimulus presses hardest at its center, so the receptor under the center fires fastest and its neighbors fire more slowly.', "Each sensory neuron also drives inhibitory interneurons that reach its neighbors' pathways.", 'The fast-firing center neuron inhibits its neighbors more than they inhibit it.', "The neighbors' signals drop much further than the center's.", 'The difference between center and edge grows, so the brain locates the stimulus more precisely.'])]),
   ("Receptors and transduction", [
     ("p", "Every sensory pathway: stimulus, receptor, sensory neuron, integration in the CNS. Some signals reach conscious perception; many are acted on subconsciously. The nervous system can modulate the information at every synapse."),
     ("table", ["Kind of receptor", "What it is", "Examples"],
      [["Simple neural receptor", "A neuron with bare, free nerve endings", "Pain and itch receptors"],
       ["Complex neural receptor", "Nerve ending wrapped in a connective tissue capsule", "Pacinian corpuscle (vibration, touch)"],
       ["Nonneural receptor", "Modified epithelial cell that releases transmitter onto a sensory neuron", "Hair cells of the ear"]]),
     ("ul", ["Accessory structures help receptors without being receptors: the cornea and lens focus light; hairs on the skin detect air movement; the pinna funnels sound.",
             "Adequate stimulus: the form of energy a receptor responds to best. A strong enough stimulus of another kind can also activate it, as a blow to the eye makes you see light.",
             "Threshold: the minimum stimulus that activates a receptor. Some respond to one photon or one odorant molecule.",
             "Transduction opens or closes ion channels, directly or through a second messenger. Most receptors depolarize as cations enter; a few hyperpolarize as K+ leaves; light closes cation channels in photoreceptors.",
             "The receptor potential is a graded potential. In a neural receptor it can trigger action potentials at the trigger zone; in a nonneural receptor it changes transmitter release onto the sensory neuron."]),
     ("defs", [("Frequency coding", "A stronger stimulus gives a bigger receptor potential and a higher firing frequency, up to a maximum, and more transmitter released at the axon terminal."),
               ("Population coding", "Receptors have different thresholds, so a stronger stimulus recruits more of them. Many receptors together carry more information than one.")]),
   ]),
   ("Receptor classes", [
     ("table", ["Class", "Adequate stimulus", "Examples and locations"],
      [["Chemoreceptor", "Chemicals that bind the receptor", "O2, pH and glucose in the blood; taste buds; olfactory epithelium"],
       ["Mechanoreceptor", "Mechanical energy: pressure, stretch, vibration, gravity, acceleration, sound", "Baroreceptors (pressure), osmoreceptors (cell stretch), touch receptors, muscle spindles, hair cells"],
       ["Thermoreceptor", "Temperature", "Skin, hypothalamus"],
       ["Photoreceptor", "Light", "Rods and cones of the retina"],
       ["Nociceptor", "Stimuli strong enough to damage tissue", "Skin, joints, muscles, organs. Your textbook covers these with pain rather than as a fifth group"]]),
   ]),
   ("What the brain is told", [
     ("table", ["Property", "How it is coded"],
      [["Modality", "Which receptors are active and where their pathway ends in the cortex: labeled line coding. Qualities within a modality, such as red, green and blue, come from different receptors"],
       ["Location", "Which receptive fields are active; the cortex is a map with neighboring receptors processed in neighboring areas. Sound is located by the difference in arrival time at the two ears"],
       ["Intensity", "Frequency coding and population coding"],
       ["Duration", "How long the train of action potentials lasts, shaped by adaptation"]]),
     ("ul", ["Stimulating the hand area of cortex during surgery is felt as a touch on the hand.",
             "One form of phantom limb pain comes from hyperactive secondary sensory neurons in the spinal cord; the brain places the pain in the missing limb.",
             "Most sensory pathways relay in the thalamus before the cortex. Smell does not. The midbrain receives visual information, the medulla receives input for sound and taste, and balance is processed mainly in the cerebellum."]),
   ]),
   ("Receptive fields and acuity", [
     ("ul", ["Receptive field: the area that changes one sensory neuron's firing.",
             "Primary (first-order) sensory neuron synapses on a secondary (second-order) neuron in the CNS.",
             "Convergence: many primary neurons onto one secondary neuron, merging their fields into one large secondary receptive field; subthreshold stimuli can sum there.",
             "Arms and legs: much convergence, large fields; two points about 20 mm apart can feel like one. Fingertips: little convergence, as little as one to one; points a few millimeters apart feel like two.",
             "Lateral inhibition: the secondary neuron nearest the stimulus inhibits its neighbors, probably by opening K+ or Cl- channels, increasing contrast so the stimulus is easier to locate. In vision it sharpens edges."]),
   ]),
   ("Adaptation and habituation", [
     ("table", ["", "Tonic (slowly adapting)", "Phasic (rapidly adapting)"],
      [["Response to a steady stimulus", "Fires rapidly, then slows but keeps firing", "Fires at onset, stops while the stimulus is constant, may fire at offset"],
       ["Reports", "The stimulus, continuously", "Change"],
       ["Examples", "Baroreceptors, irritant receptors, some touch receptors, proprioceptors", "Smell receptors; Pacinian corpuscles"]]),
     ("ul", ["Mechanisms of adaptation: K+ channels open and repolarize the receptor, Na+ channels inactivate, or biochemical pathways change its responsiveness. Accessory structures can help: small middle ear muscles dampen loud sounds.",
             "After a phasic receptor adapts, only a stronger stimulus or removing the stimulus so the receptor resets produces a new signal.",
             "Perceptual threshold: the stimulus intensity needed for awareness. Habituation raises it by inhibitory modulation in secondary and higher neurons; attention can override it. Adaptation happens at the receptor; habituation happens in the CNS."]),
   ]),
  ]),

 dict(slug="pathways-pain", file="biol005-w05-pathways-pain-walkthrough-notes.html",
  title="Spinal pathways, touch and pain", walk="biol005-w05-pathways-pain-guided.html",
  comps="Week 5 competencies 5, 13 and 14",
  sections=[
   ("Step by step: where the signal travels", [('h3', 'Fine touch, vibration and proprioception: the dorsal column pathway, neuron by neuron'), ('ol', ['First neuron: starts at a receptor in the skin, muscle or joint. Its cell body is in the dorsal root ganglion. Its axon enters the cord through the dorsal root and climbs up the dorsal column on the same side, without synapsing in the cord.', 'First synapse: in the medulla, in the dorsal column nuclei.', 'Second neuron: its axon crosses the midline in the medulla and climbs on the opposite side to the thalamus.', 'Second synapse: in the thalamus.', 'Third (tertiary) neuron: runs from the thalamus to the primary somatic sensory cortex, the postcentral gyrus, on the side opposite the body part. Branches also go to the cerebellum.']), ('h3', 'Pain, temperature and coarse touch: the spinothalamic tract, neuron by neuron'), ('ol', ['First neuron: starts at a nociceptor or thermoreceptor. Its cell body is in the dorsal root ganglion. Its axon enters through the dorsal root and synapses almost right away in the dorsal horn.', 'First synapse: in the dorsal horn of the spinal cord, within a segment or two of where it entered.', 'Second neuron: its cell body is in the dorsal horn. Its axon crosses the midline inside the cord and climbs on the opposite side all the way to the thalamus.', 'Second synapse: in the thalamus.', 'Third (tertiary) neuron: runs from the thalamus to the somatosensory cortex on the side opposite the body part. Branches also go to the limbic system and hypothalamus.']), ('h3', 'Voluntary movement: the corticospinal tract, neuron by neuron'), ('ol', ['Upper motor neuron: its cell body is in the primary motor cortex, the precentral gyrus.', 'Its axon runs down through the brainstem to the bottom of the medulla, to the pyramids.', 'Most of the axons, about 85 to 90 percent, cross the midline there.', 'They descend on the opposite side of the spinal cord, in the lateral white matter.', 'Synapse: in the ventral horn, on a lower motor neuron, directly or through an interneuron.', 'Lower motor neuron: its cell body is in the ventral horn. Its axon leaves through the ventral root, runs in the spinal nerve, and ends on the muscle at a neuromuscular junction.']), ('h3', 'The pain gate, step by step (the classic gate control model)'), ('ol', ['A bumped shin fires nociceptors. Their signal reaches the dorsal horn and excites the projection neuron that carries pain up to the brain.', 'Rubbing the shin fires the large touch fibers from the same skin.', 'The touch fibers excite an inhibitory interneuron in the dorsal horn.', 'The interneuron inhibits the projection neuron.', 'Fewer pain signals leave the dorsal horn for the brain, so the pain feels less.']), ('h3', "The body's own painkillers, step by step"), ('ol', ['Descending pathways from the brainstem activate interneurons in the dorsal horn.', 'The interneurons release enkephalin, an endogenous opioid.', "Before the synapse: enkephalin binds opioid receptors on the nociceptor's terminal, less Ca2+ enters, and less substance P and glutamate are released.", 'After the synapse: enkephalin binds opioid receptors on the projection neuron, K+ channels open, and the neuron hyperpolarizes.', 'Fewer pain signals travel up the spinothalamic tract.']), ('h3', 'Referred pain, step by step'), ('ol', ['Heart muscle without enough oxygen fires visceral pain fibers.', 'They enter the same segments of the spinal cord as sensory fibers from the skin of the left arm.', 'Both sets of fibers converge on the same projection neurons in the dorsal horn.', 'The signal climbs to the brain on that shared line.', 'The brain usually receives signals on that line from the skin, so it places the pain in the left arm.'])]),
   ("Inside the spinal cord", [
     ("ul", ["Four regions, named for the vertebrae beside them: cervical, thoracic, lumbar and sacral. Each region has segments, and each segment gives rise to a pair of spinal nerves.",
             "Just before joining the cord, each spinal nerve splits into a dorsal root, sensory in, whose dorsal root ganglion holds the sensory cell bodies, and a ventral root, out to muscles and glands.",
             "Gray matter, H-shaped, in the center: cell bodies, dendrites, unmyelinated axons and synapses. A cluster of cell bodies in the CNS is a nucleus; outside the CNS it is a ganglion.",
             "Dorsal (posterior) horn: sensory fibers synapse on interneurons, in separate somatic and visceral sensory nuclei. Ventral (anterior) horn: motor neuron cell bodies, in somatic motor and autonomic nuclei; the autonomic nuclei sit in the small lateral horn.",
             "White matter: mostly myelinated axons, bundled into tracts, the CNS equivalent of nerves. A group of tracts is a column.",
             "Ascending tracts, sensory and going up, run in the dorsal and outer lateral white matter. Descending tracts, mostly motor and going down, run in the ventral and inner lateral white matter. Propriospinal tracts stay within the cord.",
             "Most corticospinal axons cross at the pyramids and descend in the lateral corticospinal tract; those that do not cross descend in the anterior corticospinal tract. Because of the pyramids, the corticospinal tract is also called the pyramidal tract.",
             "Interneurons lie entirely within the CNS. In the cord they route sensory information up to the brain, bring commands down to motor neurons, and modify information as it passes through.",
             "The cord is a self-contained integrating center for spinal reflexes, which usually also send sensory information up to the brain.",
             "Damage to a dorsal root ganglion (shingles) affects sensation in one strip of skin. Damage to the ventral horn (polio) causes weakness with sensation spared."]),
     ("table", ["Part", "Gray or white matter", "What it is"],
      [["Horn", "Gray", "A region of cell bodies and synapses"],
       ["Root", "Neither: outside the cord", "A branch of a spinal nerve just before it joins the cord"],
       ["Tract", "White", "A bundle of axons running up or down"],
       ["Column", "White", "A group of tracts"]]),
   ]),
   ("Three long pathways", [
     ("table", ["Tract", "Carries", "Direction", "Where it crosses the midline", "First synapse"],
      [["Dorsal column", "Fine touch, vibration, proprioception", "Up", "Medulla", "Medulla (dorsal column nuclei)"],
       ["Spinothalamic", "Pain, temperature", "Up", "Spinal cord, within a segment or two of entry", "Dorsal horn of the cord"],
       ["Corticospinal", "Voluntary movement", "Down", "Bottom of the medulla (the pyramids)", "Ventral horn motor neuron"]]),
     ("ul", ["Both sensory pathways relay in the thalamus before reaching the somatosensory cortex.",
             "Corticospinal neurons in the cortex are upper motor neurons; the motor neurons in the ventral horn are lower motor neurons.",
             "Each side of the brain senses and moves the opposite side of the body."]),
     ("h3", "Brown-Séquard syndrome: a cut through one half of the cord"),
     ("ul", ["Same side as the cut, below it: loss of fine touch, vibration and position sense, and loss of voluntary movement.",
             "Opposite side, below it: loss of pain and temperature.",
             "The split pattern locates the lesion in the cord. Above the medulla all three pathways have crossed, so a brain lesion takes everything from the same side of the body."]),
   ]),
   ("Where these pathways go in the brain", [
     ("table", ["Region", "Role on these pathways"],
      [["Medulla, at the pyramids", "Most corticospinal axons cross the midline here, so each side of the brain controls the opposite side of the body"],
       ["Pons", "Relay between the cerebrum and the cerebellum"],
       ["Midbrain", "Eye movement; relays for visual and auditory reflexes"],
       ["Reticular formation, through the brain stem", "Arousal, muscle tone and stretch reflexes, and pain modulation"],
       ["Thalamus", "Relay and integrating station for almost all sensory information on its way to the cerebrum; smell is the exception"],
       ["Cerebellum", "Receives muscle and joint position information and coordinates movement and posture automatically"],
       ["Primary somatic sensory cortex, parietal lobe", "Touch, temperature, pain, itch and body position. Damage dulls sensation on the opposite side of the body"],
       ["Primary motor cortex and motor association area, frontal lobe", "Start voluntary movement; pyramidal cells send their axons down the corticospinal tract"],
       ["Visual cortex, occipital lobe", "Vision"],
       ["Auditory cortex, temporal lobe", "Hearing"],
       ["Olfactory cortex, a small region of the temporal lobe", "Smell"],
       ["Gustatory cortex, in the insula", "Taste"]]),
     ("p", "Simple reflexes such as the knee jerk are integrated in the spinal cord or the brain stem, but the brain can still modify or override them."),
   ]),
   ("Somatic senses and their receptors", [
     ("p", "Four somatic senses: touch, proprioception, temperature, and nociception (pain and itch). All are transduced by mechanical, thermal or chemical energy opening ion channels, such as Piezo channels for pressure and TRP channels for temperature and pain. Primary sensory neurons are pseudounipolar, with cell bodies in the dorsal root ganglia."),
     ("table", ["Receptor", "Stimulus", "Where", "Adaptation"],
      [["Free nerve endings", "Temperature, noxious stimuli, hair movement", "Around hair roots and under the skin surface", "Variable"],
       ["Meissner corpuscle", "Flutter, stroking", "Superficial skin", "Rapid"],
       ["Pacinian corpuscle", "Vibration; large receptive fields", "Deep skin", "Rapid"],
       ["Ruffini corpuscle", "Skin stretch", "Deep skin", "Slow"],
       ["Merkel receptor", "Steady pressure, texture; Merkel cell with Piezo2 releases transmitter onto the nerve ending; densest in fingertips", "Superficial skin", "Slow"]]),
     ("ul", ["Thermoreceptors in the skin are free nerve endings. Cold receptors respond below body temperature; warm receptors from 37 °C (98.6 °F) to about 45 °C (113 °F); above that, nociceptors produce painful heat. Cold receptors outnumber warm ones.",
             "TRPV1 channels open with damaging heat and with capsaicin (chili peppers). TRPM8 opens with cold and with menthol.",
             "The somatosensory cortex, in the parietal lobe, has a sensory field for each body part, with columns for each kind of receptor. Area tracks sensitivity, and the map changes with use (Braille readers) and after loss of a body part (phantom limb pain when reorganization goes wrong). The brain has no pain receptors."]),
   ]),
   ("Pain and its modulation", [
     ("table", ["Fiber", "Structure", "Speed", "Carries"],
      [["A-beta", "Large, myelinated", "30 to 70 m/s", "Mechanical stimuli (touch)"],
       ["A-delta", "Small, myelinated", "12 to 30 m/s", "Fast pain, cold, mechanical stimuli"],
       ["C", "Small, unmyelinated", "0.5 to 2 m/s", "Slow pain, heat, cold, mechanical stimuli, itch"]]),
     ("ul", ["Nociceptors: free nerve endings in skin, joints, muscles, bones and organs, not in the brain or spinal cord. They respond to stimuli that cause or could cause tissue damage.",
             "Fast pain is sharp and localized (A-delta); slow pain is dull and diffuse (C). Itch (pruritus) comes from a subtype of nociceptor fiber; scratching seems to interrupt it.",
             "Nociceptor fibers end in the dorsal horn and drive two things: protective spinal reflexes such as withdrawal, and ascending pathways to the thalamus and cortex. Branches to the limbic system and hypothalamus add suffering and autonomic reactions (nausea, sweating, fainting).",
             "Deep somatic pain comes from muscle, as in the burn of exercise or ischemia. Visceral pain is poorly localized.",
             "Referred pain: visceral and somatic nociceptors converge on one ascending tract; the brain assigns the pain to the skin. Heart: neck, shoulder, left arm. Gallbladder irritating the diaphragm: right shoulder and neck.",
             "Inflammatory pain: histamine, prostaglandins and substance P at an injury activate or sensitize nociceptors by lowering their threshold. Aspirin inhibits prostaglandins.",
             "Chronic pain lasts weeks or months and reflects changes in the nervous system; neuropathic pain, such as diabetic neuropathy, comes from damage to the somatosensory system.",
             "Gate control theory: touch fibers excite an inhibitory interneuron that inhibits the pain projection neuron in the dorsal horn. Your textbook notes this classic model rests on inaccurate assumptions and leaves out spinal glia; what holds is that pain can be modulated in the cord.",
             "Descending pathways from the brain inhibit nociceptor neurons in the cord, as in emergencies."]),
     ("defs", [("Endogenous opioids", "Endorphins, enkephalins and dynorphins. Enkephalins and dynorphins are released by neurons in pain pathways; beta-endorphin comes from the anterior pituitary, from the same prohormone as ACTH. Opioid receptors decrease transmitter release from primary sensory neurons and inhibit secondary neurons. Long-term opioid drugs cause tolerance."),
               ("Other pain relief", "Capsaicin patches (TRP channels), ziconotide (blocks Ca2+ channels, given into the CSF), neuromodulation with electrodes, and acupuncture.")]),
   ]),
  ]),

 dict(slug="csf-bbb", file="biol005-w05-csf-bbb-walkthrough-notes.html",
  title="Cerebrospinal fluid and the blood-brain barrier", walk="biol005-w05-csf-bbb-guided.html",
  comps="Week 5 competency 6",
  sections=[
   ("Step by step: where the signal travels", [
     ("h3","Where cerebrospinal fluid travels, step by step"),
     ("ol",["Choroid plexus cells pump Na+ and other solutes from the plasma into the ventricles; water follows by osmosis.",
            "The fluid flows from the two lateral ventricles (the first and second) into the third ventricle.",
            "It flows through the cerebral aqueduct, a narrow channel, into the fourth ventricle.",
            "It leaves the fourth ventricle and enters the subarachnoid space, between the arachnoid membrane and the pia mater.",
            "It circulates around the brain and down around the spinal cord.",
            "It is reabsorbed through the arachnoid villi into a venous sinus and returns to the blood. The whole volume turns over about three times a day."]),
     ("h3","How glucose gets from the blood into a neuron, step by step"),
     ("ol",["Glucose arrives in the blood of a brain capillary.",
            "Tight junctions close the gaps between the endothelial cells, so it cannot slip between them.",
            "A glucose transporter (GLUT1) carries it into the endothelial cell, and another carries it out on the brain side, by facilitated diffusion.",
            "Neurons take it up and use it for aerobic metabolism. Astrocytes also take it up and pass lactate to neurons."]),
   ]),
   ("Protecting the brain", [
     ("ul", ["Brain and spinal cord tissue is soft, with little extracellular matrix, so it relies on outside support: bone, three membranes, and fluid.",
             "Gray matter: cell bodies, dendrites and unmyelinated axons. Clusters of cell bodies in the CNS are nuclei; outside the CNS they are ganglia.",
             "White matter: mostly myelinated axons. Bundles of axons in the CNS are tracts, the CNS equivalent of nerves."]),
     ("table", ["Membrane, skull inward", "What it is like", "What goes with it"],
      [["Dura mater", "Outermost and thickest", "Venous sinuses that drain the brain"],
       ["Arachnoid membrane", "Middle, loosely attached to the pia", "The subarachnoid space beneath it, filled with cerebrospinal fluid"],
       ["Pia mater", "Innermost and thin, clings to the brain and cord", "Arteries that supply the brain"]]),
   ]),
   ("Cerebrospinal fluid", [
     ("defs", [("Choroid plexus", "Capillaries covered by a transporting epithelium derived from the ependyma, on the walls of the ventricles. Secretes cerebrospinal fluid."),
               ("Physical protection", "Buoyancy makes the brain act about 30 times lighter, reducing pressure on its vessels and nerves; the fluid cushions the brain during a blow because water barely compresses."),
               ("Chemical protection", "The choroid plexus is selective, so the fluid differs from plasma: less K+, more H+ (lower pH), similar Na+, very little protein, no blood cells.")]),
     ("ul", ["About 150 mL is present at any time; about 500 mL is made each day.",
             "Lumbar puncture (spinal tap): a sample taken from the subarachnoid space in the lower back, below the end of the spinal cord. Protein or blood cells in it suggest infection.",
             "Aqueductal stenosis: a blocked cerebral aqueduct makes the lateral and third ventricles enlarge while the fourth stays normal. If all four enlarge, the block is farther along, in the subarachnoid space. Build-up of fluid is hydrocephalus."]),
   ]),
   ("The blood-brain barrier", [
     ("ul", ["Most brain capillaries have tight junctions between their endothelial cells, blocking movement between the cells.",
             "Tight junctions form in response to paracrines from astrocyte foot processes and from pericytes, contractile cells around the capillary that also regulate its blood flow.",
             "The barrier is selective transport: carriers move nutrients in, other transporters move wastes out, and any water-soluble molecule without a carrier stays out."]),
     ("table", ["Substance", "Crosses?", "How"],
      [["Oxygen", "Yes, freely", "Small and nonpolar: diffuses through the membranes"],
       ["Small lipid-soluble drugs (anesthetics, older antihistamines)", "Yes", "Dissolve through the endothelial membranes"],
       ["Glucose", "Yes", "Membrane transporters (GLUT1), facilitated diffusion"],
       ["L-dopa", "Yes", "Amino acid transporter"],
       ["Dopamine, large proteins, other water-soluble molecules with no carrier", "No", "No gaps and no carrier"]]),
     ("ul", ["Older antihistamines were lipid soluble, crossed the barrier and caused drowsiness; newer ones are less lipid soluble and do not.",
             "Parkinson's: dopamine cannot cross, so L-dopa is given; neurons convert it to dopamine inside the brain.",
             "Areas without the barrier: the hypothalamus, whose neurosecretory hormones must enter the portal capillaries to the anterior pituitary, and the vomiting center in the medulla, which monitors the blood for toxins."]),
   ]),
   ("The brain's fuel", [
     ("ul", ["The brain uses about one fifth of the body's oxygen at any moment and, by some estimates, about half of its glucose.",
             "Neurons normally use only glucose for fuel, which is one reason blood glucose is so closely defended.",
             "Sustained high blood glucose makes barrier cells down-regulate their glucose transporters. If glucose then falls, the brain cannot get enough fast enough: confusion, irritability, slurred speech, and eventually unconsciousness."]),
   ]),
  ]),

 dict(slug='vision', file='biol005-w05-vision-walkthrough-notes.html',
  title='Vision', walk='biol005-w05-vision-guided.html',
  comps='Week 5 competencies 16 to 19',
  sections=[('Step by step: where the signal travels', [('h3', 'The path of light through the eye'), ('ol', ['Cornea, which does about two thirds of the refraction.', 'Aqueous humor in the anterior chamber.', 'The pupil, the opening in the iris.', 'The lens, which adjusts the focus.', 'The vitreous body in the vitreous chamber.', 'The retina. Light passes through the ganglion cell and bipolar cell layers to reach the rods and cones at the back, against the retinal pigment epithelium (except at the fovea, where the inner layers are pushed aside).']), ('h3', 'Phototransduction in a rod, step by step'), ('ol', ['Dark: cGMP is high, CNG channels are open, Na+ and Ca2+ enter while K+ leaks out, the rod sits near −40 mV, and it releases glutamate continuously.', 'A photon is absorbed; retinal changes shape and is released from opsin (bleaching).', 'Activated opsin turns on the G protein transducin.', "Transducin's cascade (through phosphodiesterase) lowers cGMP.", 'CNG channels close; Na+ and Ca2+ entry stops while K+ keeps leaving.', 'The rod hyperpolarizes toward −70 mV, in proportion to the light.', 'Fewer voltage-gated Ca2+ channels in the terminal are open, so glutamate release falls.', 'Recovery: retinal moves to the retinal pigment epithelium, reverts to its inactive form, and returns to rejoin opsin. This is slow, which is why dark adaptation takes time.']), ('h3', 'The path of the signal, from photoreceptor to cortex'), ('ol', ['Photoreceptor (rod or cone): graded potentials; light lowers its glutamate release.', 'Bipolar cell: graded potentials. ON bipolar cells are excited by light (less glutamate), OFF bipolar cells are inhibited by it. Horizontal cells add lateral inhibition.', 'Ganglion cell: fires the first action potentials; amacrine cells modulate the bipolar-to-ganglion signal. Ganglion cell axons form the optic nerve and leave at the optic disk (blind spot).', 'Optic chiasm: fibers from the inner (nasal) half of each retina cross; fibers from the outer half stay on their own side.', 'Optic tract to the lateral geniculate body of the thalamus.', 'Visual cortex in the occipital lobe. Some fibers go to the midbrain for eye movements and the pupillary reflex.']), ('h3', 'The pupillary light reflex, step by step'), ('ol', ['Light reaches the retina of one eye.', "The signal travels in that eye's optic nerve, cranial nerve II.", 'It reaches the thalamus; collateral pathways go to the midbrain.', 'In the midbrain the signal diverges to both sides.', 'Parasympathetic fibers in cranial nerve III contract the pupillary sphincter of each eye, and both pupils constrict (the consensual reflex).']), ('h3', 'Accommodation for a near object, step by step'), ('ol', ['You look from something far away to something near; its light rays are no longer parallel.', 'Parasympathetic signals make the ciliary muscle contract.', 'The muscle ring gets smaller, releasing tension on the zonules.', 'The elastic lens rounds up, shortening its focal length and bending light more.', 'The near image lands on the retina.'])]), ('Structures of the eye', [('table', ['Structure', 'What it does'], [['Orbit', 'Bony cavity that protects the eye'], ['Extrinsic eye muscles', 'Six skeletal muscles that move the eye; cranial nerves III, IV and VI'], ['Lacrimal apparatus', 'Lacrimal gland secretes tears (stimulated by parasympathetic fibers of cranial nerve VII); the nasolacrimal duct drains them into the nasal cavity'], ['Sclera', 'Outer connective tissue wall; the cornea is its clear front continuation'], ['Iris and pupil', 'Pigmented ring and its opening; sphincter (parasympathetic) constricts, radial dilator (sympathetic) dilates'], ['Lens and zonules', 'Clear elastic disk on inelastic ligaments attached to the ciliary muscle'], ['Aqueous humor', 'Low-protein fluid in the anterior chamber, secreted by the ciliary epithelium, drained through the canal of Schlemm; nourishes the cornea'], ['Vitreous body', 'Clear gel filling the vitreous chamber; maintains the shape of the eyeball'], ['Retina', 'Layers of photoreceptors and neurons; the fovea and macula give the sharpest vision; the optic disk is the blind spot'], ['Retinal pigment epithelium', 'Dark layer behind the photoreceptors; absorbs stray light, recycles retinal, phagocytizes the old disks at the tips of the outer segments, and helps form a blood-retinal barrier']]), ('ul', ['Glaucoma: degeneration of the optic nerve; raised intraocular pressure from blocked aqueous humor drainage is a risk factor, though not the only cause. Leading cause of blindness worldwide.', 'Macular degeneration: loss of central vision; peripheral vision remains.'])]), ('Focusing light', [('ul', ['Refraction: light bends when passing between materials of different density. About two thirds happens at the cornea, one third at the lens.', 'A convex lens converges light to a focal point; a concave lens spreads it. The focal length is fixed unless the lens changes shape; a rounder lens has a shorter focal length.', 'Objects about 6 meters (20 feet) or more away send parallel rays and focus with a flatter lens.', 'Accommodation: the ciliary muscle contracts (parasympathetic), the zonules slacken, the lens rounds. The near point of accommodation is the closest distance in focus.', 'Accommodation declines from childhood; by 40 it is about half of what it was at 10, and by 60 many people lose it (presbyopia).']), ('table', ['', 'Far object', 'Near object (accommodation)'], [['Ciliary muscle', 'Relaxed', 'Contracted'], ['Zonules', 'Taut', 'Slack'], ['Lens', 'Flatter, less bending', 'Rounder, more bending']]), ('table', ['Condition', 'Cause', 'Focus falls', 'Corrective lens'], [['Myopia (nearsighted)', 'Eyeball too long or cornea too curved', 'In front of the retina', 'Concave'], ['Hyperopia (farsighted)', 'Eyeball too short or cornea too flat', 'Behind the retina', 'Convex'], ['Presbyopia', 'Stiff lens; accommodation lost', 'Behind the retina for near objects', 'Convex reading lens'], ['Astigmatism', 'Cornea not a perfect dome', 'Distorted image', 'Lens shaped to the uneven curve']]), ('defs', [('Pupillary light reflex', 'Light in one eye constricts both pupils (consensual reflex). If light in the left eye constricts the right pupil but not the left, the efferent path to the left eye is broken. If it constricts neither while light in the right eye constricts both, the afferent path from the left eye is broken.'), ('Depth of field', 'A narrower pupil lets a narrower beam in, keeping more of the scene in focus.')])]), ('Photoreceptors and phototransduction', [('table', ['', 'Rods', 'Cones'], [['Light needed', 'Dim; night vision', 'Bright; daytime vision'], ['Color', 'No (black and white)', 'Yes: red, green and blue cones'], ['Where', 'Most of the retina; far outnumber cones', 'Only cones in the fovea'], ['Pigment', 'Rhodopsin', 'Three pigments related to rhodopsin'], ['Convergence', 'High: sensitive, low acuity', 'Low at the fovea, as little as one to one: high acuity']]), ('ul', ['Each photoreceptor has an outer segment with pigment disks, an inner segment with the nucleus and organelles, and a synaptic terminal releasing glutamate onto bipolar cells.', 'Rhodopsin = opsin + retinal (from vitamin A). Bleaching releases retinal; its slow recycling explains slow dark adaptation.', 'Color comes from comparing the three cone types; color blindness is an inherited defect in one or more cone types, red-green being best known.', 'Visible light runs from about 400 nm (violet) to 700 nm (red).'])]), ('Processing in the retina and beyond', [('ul', ['Five kinds of retinal neuron: photoreceptors, bipolar cells, ganglion cells, horizontal cells (lateral inhibition) and amacrine cells (modulate bipolar-to-ganglion signals). Glia include astrocytes and Müller cells.', 'Convergence: many photoreceptors onto one bipolar cell, many bipolar cells onto one ganglion cell; minimal at the fovea, greatest at the edges.', 'ON bipolar cells have a metabotropic glutamate receptor that hyperpolarizes them, so they are activated by light. OFF bipolar cells have an ionotropic receptor that depolarizes them, so they are excited in the dark.', 'Ganglion cell receptive fields have a center and a surround (on-center or off-center). Strong contrast gives a strong response; even light gives a weak one, so the retina reports contrast.', 'M ganglion cells: movement. P ganglion cells: form and fine detail. Melanopsin-containing ganglion cells send light information to the suprachiasmatic nucleus for circadian rhythms; most sensitive to blue light.', 'The image on the retina is upside down; the brain reverses it.', 'Left visual field of both eyes goes to the right visual cortex, and right to left. The binocular zone gives depth perception; the monocular zones are seen in two dimensions.', 'The lateral geniculate body and the visual cortex keep a map of the visual field; the cortex sorts information by form, color and movement.']), ('table', ['Lesion', 'Field loss'], [['One optic nerve, before the chiasm', 'All vision in that eye'], ['Middle of the chiasm (pituitary tumor)', "Outer (temporal) half of each eye's field: bitemporal hemianopia, often unnoticed for a long time"]])])]),

 dict(slug="hearing-balance", file="biol005-w05-hearing-balance-walkthrough-notes.html",
  title="Hearing, balance, taste and smell", walk="biol005-w05-hearing-balance-guided.html",
  comps="Week 5 competencies 20 to 23",
  sections=[
   ("Step by step: where the signal travels", [('h3', 'The path of sound into the cochlea'), ('ol', ['The outer ear funnels sound waves down the ear canal.', 'The tympanic membrane (eardrum) vibrates.', 'The malleus, incus and stapes carry the vibration across the middle ear.', 'The stapes pushes the oval window in and out.', 'The pressure wave travels along the vestibular duct, around the helicotrema at the tip, and back along the tympanic duct.', 'As the wave passes, the basilar membrane bows up and down; the round window bulges out and in to let the fluid move.']), ('h3', 'Hair cell transduction, step by step'), ('ol', ['At rest, about 10 percent of the hair cell channels are open, so the sensory neuron fires a steady tonic signal.', 'The basilar membrane moves, carrying the organ of Corti with it; the stereocilia bend against the tectorial membrane.', 'Bending toward the tallest stereocilium stretches the tip links and opens more mechanically gated cation channels.', 'K+ flows in from the high-K+ endolymph of the cochlear duct and the hair cell depolarizes.', 'Voltage-gated Ca2+ channels at the base open and more neurotransmitter is released.', 'The primary sensory neuron fires faster. Bending the other way closes channels, hyperpolarizes the cell, and slows or stops firing.']), ('h3', 'The path of the hearing signal to the cortex'), ('ol', ['Primary sensory neurons, with cell bodies in the spiral ganglion of the cochlea, carry action potentials in the cochlear branch of cranial nerve VIII.', 'They synapse in the cochlear nucleus in the medulla.', 'Signals go to the superior olivary nucleus on both sides; branches also go to the cerebellum.', 'They climb to the inferior colliculus in the midbrain.', 'They relay in the medial geniculate nucleus of the thalamus.', 'They reach the auditory cortex in the temporal lobe. Each ear sends information to both sides of the brain, so damage to one side of the brain rarely makes one ear deaf.']), ('h3', 'Sensing a head turn, step by step'), ('ol', ['The head turns; the bony skull and the canal walls turn with it.', 'The endolymph lags behind because of inertia.', 'In the ampulla, the drag of the endolymph bends the cupula of the crista opposite to the turn.', 'Hair cell cilia embedded in the cupula bend; bending toward the kinocilium depolarizes the cell, bending away hyperpolarizes it.', 'Transmitter release onto vestibular sensory neurons rises or falls.']), ('h3', 'The path of the balance signal'), ('ol', ['Hair cells release transmitter onto primary sensory neurons of the vestibular branch of cranial nerve VIII.', 'The neurons either synapse in the vestibular nuclei of the medulla or run without synapsing to the cerebellum, the main site for equilibrium processing.', 'From the vestibular nuclei, pathways go to the cerebellum, to the motor neurons that move the eyes (keeping the gaze steady as the head turns), and up through the reticular formation and thalamus to the cortex.']), ('h3', 'Sour taste, step by step'), ('ol', ['Food acid dissolves in saliva and H+ reaches a type III (presynaptic) taste cell.', 'H+ enters through a proton channel.', 'A K+ leak channel closes, then Na+ channels and Ca2+ channels open, depolarizing the cell.', 'Ca2+ entry triggers exocytosis of serotonin.', 'Serotonin excites the primary sensory (gustatory) neuron.']), ('h3', 'Sweet, bitter and umami taste, step by step'), ('ol', ['The tastant dissolves in saliva and binds a G protein-coupled receptor on a type II (receptor) cell: T1R for sweet and umami, T2R for bitter.', 'The G protein gustducin activates the phospholipase C pathway.', 'Ca2+ is released from intracellular stores.', 'Ca2+ opens Ca2+-activated Na+ channels; Na+ entry depolarizes the cell.', 'ATP leaves the cell through the CALHM1 channel, not by exocytosis, and excites the primary sensory neuron. Support cells break down the leftover ATP.']), ('h3', 'The path of taste to the cortex'), ('ol', ['Gustatory neurons carry the signal in cranial nerves VII, IX and X.', 'They synapse in the medulla.', 'The signal relays in the thalamus.', 'It reaches the gustatory cortex in the insula. The brain reads the taste from which neuron populations respond most strongly.']), ('h3', 'The path of smell'), ('ol', ['An odorant dissolves in the mucus made by olfactory (Bowman\'s) glands.', 'It binds an olfactory receptor, a G protein-coupled receptor, on the cilia (the dendrites) of an olfactory sensory neuron, a bipolar neuron.', 'The G protein Golf raises cAMP; cAMP-gated cation channels open and the neuron depolarizes.', 'If the receptor potential reaches threshold, an action potential travels along the axon. The axons form cranial nerve I and pass through the bone to the olfactory bulb.', 'They synapse on secondary neurons in the olfactory bulb, many converging on each.', 'The olfactory tract carries the signal to the olfactory cortex, bypassing the thalamus, and to the amygdala and hippocampus of the limbic system.'])]),
   ("Hearing", [
     ("ol", ["Sound, a pressure wave in air, vibrates the tympanic membrane.",
             "The ossicles (malleus, incus, stapes) carry the vibration to the oval window. The eardrum is about 20 times the area of the oval window, so the same force on a smaller area gives a higher pressure, enough to move fluid instead of reflecting off it.",
             "The oval window pushes on the cochlear fluid; the round window bulges out to let the fluid move.",
             "The pressure wave moves the basilar membrane.",
             "Stereocilia bend toward the tallest; tip links pull mechanically gated channels open.",
             "Potassium enters from the high-potassium endolymph and the hair cell depolarizes.",
             "Voltage-gated calcium channels open at the base and glutamate is released onto auditory nerve fibers, which fire faster."]),
     ("ul", ["Pitch is coded by place: high frequencies move the basilar membrane most near the oval window, where it is narrow and stiff; low frequencies move it most near the helicotrema, where it is wide and flexible.",
             "The cochlea has three ducts: the vestibular duct (from the oval window), the cochlear duct (endolymph, high K+, with the organ of Corti on the basilar membrane and the tectorial membrane above), and the tympanic duct (to the round window). The vestibular and tympanic ducts connect at the helicotrema.",
             "Loudness is coded by rate: bigger movement, more transmitter, faster firing, more fibers recruited.",
             "Hair cells make graded receptor potentials, not action potentials."]),
   ]),
   ("Hearing loss and the tuning fork tests", [
     ("defs", [("Conductive loss", "Sound cannot get through the outer or middle ear (earwax, fluid, stiff ossicles)."),
               ("Sensorineural loss", "Damage to the cochlea or the auditory nerve."),
               ("Bone conduction", "Vibration carried through the skull straight to the cochlea, bypassing the outer and middle ear.")]),
     ("table", ["", "Weber (fork on the midline)", "Rinne (bone, then air, same ear)"],
      [["Normal", "Heard equally or in the middle", "Air longer than bone"],
       ["Conductive loss in one ear", "Louder in the affected ear", "Bone longer than air in the affected ear"],
       ["Sensorineural loss in one ear", "Louder in the good ear", "Air longer than bone, both shorter in the affected ear"]]),
     ("p", "Weber alone shows the ears differ but not which kind of loss; Rinne in the ear Weber points to tells you."),
   ]),
   ("Balance (equilibrium)", [
     ("ul", ["Equilibrium has a dynamic component (movement through space) and a static component (head position). The brain combines the inner ear with proprioceptors and vision.",
             "Vestibular apparatus (membranous labyrinth): the utricle and saccule (otolith organs) and three semicircular canals that join the utricle. It is filled with endolymph, high in K+ and low in Na+, secreted continuously and drained into a dural venous sinus.",
             "Vestibular hair cells have a kinocilium at one side of the bundle. Bending toward it depolarizes the cell; bending away hyperpolarizes it. The cells are tonically depolarized at rest."]),
     ("table", ["", "Semicircular canals", "Utricle and saccule (otolith organs)"],
      [["Detects", "Rotational acceleration", "Linear acceleration and head position"],
       ["Sensory structure", "Crista in the ampulla: hair cells with cilia in a gel cupula spanning the ampulla", "Macula: hair cells with cilia in the otolith membrane, topped with otoliths (calcium carbonate and protein)"],
       ["How hairs bend", "Endolymph lags behind and drags the cupula opposite the turn", "Otoliths slide with gravity or acceleration, dragging the otolith membrane"],
       ["Specifics", "Horizontal: turning, shaking the head no. Superior: nodding yes, somersault. Posterior: tilting toward a shoulder, cartwheel", "Utricle (horizontal macula): forward acceleration, deceleration, head tilt. Saccule (vertical macula): vertical forces, such as an elevator"]]),
     ("ul", ["Steady spin: the endolymph catches up and the turning signal fades. Sudden stop: the fluid keeps moving, bending the cupula the other way, so you feel yourself turning. Dancers spot to avoid this.",
             "Positional vertigo: loose otoliths float into the semicircular canals, causing brief dizziness with changes in position.",
             "Meniere's disease: excess endolymph raises inner ear pressure, causing episodes of vertigo and nausea, tinnitus, low-tone hearing loss and a feeling of fullness in the ear."]),
   ]),
   ("Taste and smell", [
     ("table", ["", "Taste (gustation)", "Smell (olfaction)"],
      [["Receptor cell", "Taste receptor cell: nonneural epithelial cell in a taste bud; each senses one taste", "Olfactory sensory neuron: a bipolar neuron, replaced about every two months from stem cells"],
       ["Stimulus", "Five tastes: sweet, sour, salty, bitter, umami (glutamate); must dissolve in saliva", "Odorants; must dissolve in mucus; each neuron has one receptor type"],
       ["Transduction", "Sour: H+ enters type III cells, serotonin released. Sweet, bitter, umami: GPCRs and gustducin on type II cells, ATP released. Salt: Na+ entry, mechanism in humans unclear", "GPCR, Golf, cAMP, cAMP-gated cation channels"],
       ["Route", "CN VII, IX, X, medulla, thalamus, gustatory cortex in the insula", "CN I, olfactory bulb, olfactory tract, olfactory cortex and limbic system, no thalamic relay"]]),
     ("ul", ["Type I taste cells are support cells; type II are receptor cells (sweet, bitter, umami); type III are presynaptic cells (sour).",
             "What each taste signals: sour, H+; salty, Na+; sweet and umami, nutritious food; bitter, possible toxins.",
             "Spicy and cooling sensations come from TRP channels on nerve endings in the mouth, carried by the trigeminal nerve (CN V). Carbonation is sensed by sour cells.",
             "Much of flavor is smell. Anosmia (loss of smell) occurs with colds and COVID-19 and can be an early sign of Alzheimer's and Parkinson's.",
             "Smell's direct route to the amygdala and hippocampus links odors with emotion and memory."]),
   ]),
  ]),
]
